exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('municipalities').del()
        .then(function () {
            // Inserts seed entries
            return knex('municipalities').insert([
                // Amazonas
                { Municipality: 'Atabapo', StateID: 1 },
                { Municipality: 'Atures', StateID: 1 },
                { Municipality: 'Autana', StateID: 1 },
                { Municipality: 'Manapiare', StateID: 1 },
                { Municipality: 'Maroa', StateID: 1 },
                { Municipality: 'Río Negro', StateID: 1 },
                // Anzoátegui
                { Municipality: 'Anaco', StateID: 2 },
                { Municipality: 'Aragua', StateID: 2 },
                { Municipality: 'Bolívar', StateID: 2 },
                { Municipality: 'Bruzual', StateID: 2 },
                { Municipality: 'Cajigal', StateID: 2 },
                { Municipality: 'Carvajal', StateID: 2 },
                { Municipality: 'Freites', StateID: 2 },
                { Municipality: 'Guanipa', StateID: 2 },
                { Municipality: 'Guanta', StateID: 2 },
                { Municipality: 'Independencia', StateID: 2 },
                { Municipality: 'Libertad', StateID: 2 },
                { Municipality: 'McGregor', StateID: 2 },
                { Municipality: 'Miranda', StateID: 2 },
                { Municipality: 'Monagas', StateID: 2 },
                { Municipality: 'Peñalver', StateID: 2 },
                { Municipality: 'Píritu', StateID: 2 },
                { Municipality: 'San Juan de Capistrano', StateID: 2 },
                { Municipality: 'Santa Ana', StateID: 2 },
                { Municipality: 'Simón Rodríguez', StateID: 2 },
                { Municipality: 'Sotillo', StateID: 2 },
                // Apure
                { Municipality: 'Achaguas', StateID: 3 },
                { Municipality: 'Biruaca', StateID: 3 },
                { Municipality: 'Muñoz', StateID: 3 },
                { Municipality: 'Páez', StateID: 3 },
                { Municipality: 'Pedro Camejo', StateID: 3 },
                { Municipality: 'Rómulo Gallegos', StateID: 3 },
                { Municipality: 'San Fernando', StateID: 3 },
                // Aragua
                { Municipality: 'Bolívar', StateID: 4 },
                { Municipality: 'Camatagua', StateID: 4 },
                { Municipality: 'Francisco Linares Alcántara', StateID: 4 },
                { Municipality: 'Girardot', StateID: 4 },
                { Municipality: 'José Ángel Lamas', StateID: 4 },
                { Municipality: 'José Félix Ribas', StateID: 4 },
                { Municipality: 'José Rafael Revenga', StateID: 4 },
                { Municipality: 'Libertador', StateID: 4 },
                { Municipality: 'Mario Briceño Iragorry', StateID: 4 },
                { Municipality: 'Ocumare de la Costa de Oro', StateID: 4 },
                { Municipality: 'San Casimiro', StateID: 4 },
                { Municipality: 'San Sebastián', StateID: 4 },
                { Municipality: 'Santiago Mariño', StateID: 4 },
                { Municipality: 'Santos Michelena', StateID: 4 },
                { Municipality: 'Sucre', StateID: 4 },
                { Municipality: 'Tovar', StateID: 4 },
                { Municipality: 'Urdaneta', StateID: 4 },
                { Municipality: 'Zamora', StateID: 4 },
                // Barinas
                { Municipality: 'Alberto Arvelo Torrealba', StateID: 5 },
                { Municipality: 'Andrés Eloy Blanco', StateID: 5 },
                { Municipality: 'Antonio José de Sucre', StateID: 5 },
                { Municipality: 'Arismendi', StateID: 5 },
                { Municipality: 'Barinas', StateID: 5 },
                { Municipality: 'Bolívar', StateID: 5 },
                { Municipality: 'Cruz Paredes', StateID: 5 },
                { Municipality: 'Ezequiel Zamora', StateID: 5 },
                { Municipality: 'Obispos', StateID: 5 },
                { Municipality: 'Pedraza', StateID: 5 },
                { Municipality: 'Rojas', StateID: 5 },
                { Municipality: 'Sosa', StateID: 5 },
                // Bolívar
                { Municipality: 'Caroní', StateID: 6 },
                { Municipality: 'Cedeño', StateID: 6 },
                { Municipality: 'El Callao', StateID: 6 },
                { Municipality: 'Gran Sabana', StateID: 6 },
                { Municipality: 'Heres', StateID: 6 },
                { Municipality: 'Piar', StateID: 6 },
                { Municipality: 'Raúl Leoni', StateID: 6 },
                { Municipality: 'Roscio', StateID: 6 },
                { Municipality: 'Sifontes', StateID: 6 },
                { Municipality: 'Sucre', StateID: 6 },
                { Municipality: 'Padre Pedro Chien', StateID: 6 },
                // Carabobo
                { Municipality: 'Bejuma', StateID: 7 },
                { Municipality: 'Carlos Arvelo', StateID: 7 },
                { Municipality: 'Diego Ibarra', StateID: 7 },
                { Municipality: 'Guacara', StateID: 7 },
                { Municipality: 'Juan José Mora', StateID: 7 },
                { Municipality: 'Libertador', StateID: 7 },
                { Municipality: 'Los Guayos', StateID: 7 },
                { Municipality: 'Miranda', StateID: 7 },
                { Municipality: 'Montalbán', StateID: 7 },
                { Municipality: 'Naguanagua', StateID: 7 },
                { Municipality: 'Puerto Cabello', StateID: 7 },
                { Municipality: 'San Diego', StateID: 7 },
                { Municipality: 'San Joaquín', StateID: 7 },
                { Municipality: 'Valencia', StateID: 7 },
                // Cojedes
                { Municipality: 'Anzoátegui', StateID: 8 },
                { Municipality: 'Falcón', StateID: 8 },
                { Municipality: 'Girardot', StateID: 8 },
                { Municipality: 'Lima Blanco', StateID: 8 },
                { Municipality: 'Pao de San Juan Bautista', StateID: 8 },
                { Municipality: 'Ricaurte', StateID: 8 },
                { Municipality: 'Rómulo Gallegos', StateID: 8 },
                { Municipality: 'San Carlos', StateID: 8 },
                { Municipality: 'Tinaco', StateID: 8 },
                // Delta Amacuro
                { Municipality: 'Antonio Díaz', StateID: 9 },
                { Municipality: 'Casacoima', StateID: 9 },
                { Municipality: 'Pedernales', StateID: 9 },
                { Municipality: 'Tucupita', StateID: 9 },
                // Falcón
                { Municipality: 'Acosta', StateID: 10 },
                { Municipality: 'Bolívar', StateID: 10 },
                { Municipality: 'Buchivacoa', StateID: 10 },
                { Municipality: 'Cacique Manaure', StateID: 10 },
                { Municipality: 'Carirubana', StateID: 10 },
                { Municipality: 'Colina', StateID: 10 },
                { Municipality: 'Dabajuro', StateID: 10 },
                { Municipality: 'Democracia', StateID: 10 },
                { Municipality: 'Falcón', StateID: 10 },
                { Municipality: 'Federación', StateID: 10 },
                { Municipality: 'Jacura', StateID: 10 },
                { Municipality: 'Los Taques', StateID: 10 },
                { Municipality: 'Mauroa', StateID: 10 },
                { Municipality: 'Miranda', StateID: 10 },
                { Municipality: 'Monseñor Iturriza', StateID: 10 },
                { Municipality: 'Palmasola', StateID: 10 },
                { Municipality: 'Petit', StateID: 10 },
                { Municipality: 'Píritu', StateID: 10 },
                { Municipality: 'San Francisco', StateID: 10 },
                { Municipality: 'Silva', StateID: 10 },
                { Municipality: 'Sucre', StateID: 10 },
                { Municipality: 'Tocópero', StateID: 10 },
                { Municipality: 'Unión', StateID: 10 },
                { Municipality: 'Urumaco', StateID: 10 },
                { Municipality: 'Zamora', StateID: 10 },
                // Guárico
                { Municipality: 'Camaguán', StateID: 11 },
                { Municipality: 'Chaguaramas', StateID: 11 },
                { Municipality: 'El Socorro', StateID: 11 },
                { Municipality: 'Francisco de Miranda', StateID: 11 },
                { Municipality: 'José Félix Ribas', StateID: 11 },
                { Municipality: 'José Tadeo Monagas', StateID: 11 },
                { Municipality: 'Juan Germán Roscio', StateID: 11 },
                { Municipality: 'Julián Mellado', StateID: 11 },
                { Municipality: 'Las Mercedes', StateID: 11 },
                { Municipality: 'Leonardo Infante', StateID: 11 },
                { Municipality: 'Pedro Zaraza', StateID: 11 },
                { Municipality: 'Ortíz', StateID: 11 },
                { Municipality: 'San Gerónimo de Guayabal', StateID: 11 },
                { Municipality: 'San José de Guaribe', StateID: 11 },
                { Municipality: 'Santa María de Ipire', StateID: 11 },
                { Municipality: 'Sebastián Francisco de Miranda', StateID: 11 },
                // Lara
                { Municipality: 'Andrés Eloy Blanco', StateID: 12 },
                { Municipality: 'Crespo', StateID: 12 },
                { Municipality: 'Iribarren', StateID: 12 },
                { Municipality: 'Jiménez', StateID: 12 },
                { Municipality: 'Morán', StateID: 12 },
                { Municipality: 'Palavecino', StateID: 12 },
                { Municipality: 'Simón Planas', StateID: 12 },
                { Municipality: 'Torres', StateID: 12 },
                { Municipality: 'Urdaneta', StateID: 12 },
                // Mérida
                { Municipality: 'Alberto Adriani', StateID: 13 },
                { Municipality: 'Andrés Bello', StateID: 13 },
                { Municipality: 'Antonio Pinto Salinas', StateID: 13 },
                { Municipality: 'Aricagua', StateID: 13 },
                { Municipality: 'Arzobispo Chacón', StateID: 13 },
                { Municipality: 'Campo Elías', StateID: 13 },
                { Municipality: 'Caracciolo Parra Olmedo', StateID: 13 },
                { Municipality: 'Cardenal Quintero', StateID: 13 },
                { Municipality: 'Guaraque', StateID: 13 },
                { Municipality: 'Julio César Salas', StateID: 13 },
                { Municipality: 'Justo Briceño', StateID: 13 },
                { Municipality: 'Libertador', StateID: 13 },
                { Municipality: 'Miranda', StateID: 13 },
                { Municipality: 'Obispo Ramos de Lora', StateID: 13 },
                { Municipality: 'Padre Noguera', StateID: 13 },
                { Municipality: 'Pueblo Llano', StateID: 13 },
                { Municipality: 'Rangel', StateID: 13 },
                { Municipality: 'Rivas Dávila', StateID: 13 },
                { Municipality: 'Santos Marquina', StateID: 13 },
                { Municipality: 'Sucre', StateID: 13 },
                { Municipality: 'Tovar', StateID: 13 },
                { Municipality: 'Tulio Febres Cordero', StateID: 13 },
                { Municipality: 'Zea', StateID: 13 },
                // Miranda
                { Municipality: 'Acevedo', StateID: 14 },
                { Municipality: 'Andrés Bello', StateID: 14 },
                { Municipality: 'Baruta', StateID: 14 },
                { Municipality: 'Brión', StateID: 14 },
                { Municipality: 'Buroz', StateID: 14 },
                { Municipality: 'Bolivar', StateID: 14 },
                { Municipality: 'Carrizal', StateID: 14 },
                { Municipality: 'Chacao', StateID: 14 },
                { Municipality: 'Cristóbal Rojas', StateID: 14 },
                { Municipality: 'El Hatillo', StateID: 14 },
                { Municipality: 'Guaicaipuro', StateID: 14 },
                { Municipality: 'Independencia', StateID: 14 },
                { Municipality: 'Lander', StateID: 14 },
                { Municipality: 'Los Salias', StateID: 14 },
                { Municipality: 'Páez', StateID: 14 },
                { Municipality: 'Paz Castillo', StateID: 14 },
                { Municipality: 'Pedro Gual', StateID: 14 },
                { Municipality: 'Plaza', StateID: 14 },
                { Municipality: 'Simón Bolívar', StateID: 14 },
                { Municipality: 'Sucre', StateID: 14 },
                { Municipality: 'Urdaneta', StateID: 14 },
                { Municipality: 'Zamora', StateID: 14 },
                // Monagas
                { Municipality: 'Acosta', StateID: 15 },
                { Municipality: 'Aguasay', StateID: 15 },
                { Municipality: 'Bolívar', StateID: 15 },
                { Municipality: 'Caripe', StateID: 15 },
                { Municipality: 'Cedeño', StateID: 15 },
                { Municipality: 'Ezequiel Zamora', StateID: 15 },
                { Municipality: 'Libertador', StateID: 15 },
                { Municipality: 'Maturín', StateID: 15 },
                { Municipality: 'Piar', StateID: 15 },
                { Municipality: 'Punceres', StateID: 15 },
                { Municipality: 'Santa Bárbara', StateID: 15 },
                { Municipality: 'Sotillo', StateID: 15 },
                { Municipality: 'Uracoa', StateID: 15 },
                // Nueva Esparta
                { Municipality: 'Antolín del Campo', StateID: 16 },
                { Municipality: 'Arismendi', StateID: 16 },
                { Municipality: 'Díaz', StateID: 16 },
                { Municipality: 'García', StateID: 16 },
                { Municipality: 'Gómez', StateID: 16 },
                { Municipality: 'Maneiro', StateID: 16 },
                { Municipality: 'Marcano', StateID: 16 },
                { Municipality: 'Mariño', StateID: 16 },
                { Municipality: 'Península de Macanao', StateID: 16 },
                { Municipality: 'Tubores', StateID: 16 },
                { Municipality: 'Villalba', StateID: 16 },
                // Portuguesa
                { Municipality: 'Agua Blanca', StateID: 17 },
                { Municipality: 'Araure', StateID: 17 },
                { Municipality: 'Esteller', StateID: 17 },
                { Municipality: 'Guanare', StateID: 17 },
                { Municipality: 'Guanarito', StateID: 17 },
                { Municipality: 'Monseñor José Vicente de Unda', StateID: 17 },
                { Municipality: 'Ospino', StateID: 17 },
                { Municipality: 'Páez', StateID: 17 },
                { Municipality: 'Papelón', StateID: 17 },
                { Municipality: 'San Genaro de Boconoíto', StateID: 17 },
                { Municipality: 'San Rafael de Onoto', StateID: 17 },
                { Municipality: 'Santa Rosalía', StateID: 17 },
                { Municipality: 'Sucre', StateID: 17 },
                { Municipality: 'Turén', StateID: 17 },
                // Sucre
                { Municipality: 'Andrés Eloy Blanco', StateID: 18 },
                { Municipality: 'Andrés Mata', StateID: 18 },
                { Municipality: 'Arismendi', StateID: 18 },
                { Municipality: 'Benítez', StateID: 18 },
                { Municipality: 'Bermúdez', StateID: 18 },
                { Municipality: 'Bolívar', StateID: 18 },
                { Municipality: 'Cajigal', StateID: 18 },
                { Municipality: 'Cruz Salmerón Acosta', StateID: 18 },
                { Municipality: 'Libertador', StateID: 18 },
                { Municipality: 'Mariño', StateID: 18 },
                { Municipality: 'Mejía', StateID: 18 },
                { Municipality: 'Montes', StateID: 18 },
                { Municipality: 'Ribero', StateID: 18 },
                { Municipality: 'Sucre', StateID: 18 },
                { Municipality: 'Valdez', StateID: 18 },
                // Táchira
                { Municipality: 'Andrés Bello', StateID: 19 },
                { Municipality: 'Antonio Rómulo Costa', StateID: 19 },
                { Municipality: 'Ayacucho', StateID: 19 },
                { Municipality: 'Bolívar', StateID: 19 },
                { Municipality: 'Cárdenas', StateID: 19 },
                { Municipality: 'Córdoba', StateID: 19 },
                { Municipality: 'Fernández Feo', StateID: 19 },
                { Municipality: 'Francisco de Miranda', StateID: 19 },
                { Municipality: 'García de Hevia', StateID: 19 },
                { Municipality: 'Guásimos', StateID: 19 },
                { Municipality: 'Independencia', StateID: 19 },
                { Municipality: 'Jáuregui', StateID: 19 },
                { Municipality: 'José María Vargas', StateID: 19 },
                { Municipality: 'Junín', StateID: 19 },
                { Municipality: 'Libertad', StateID: 19 },
                { Municipality: 'Libertador', StateID: 19 },
                { Municipality: 'Lobatera', StateID: 19 },
                { Municipality: 'Michelena', StateID: 19 },
                { Municipality: 'Panamericano', StateID: 19 },
                { Municipality: 'Pedro María Ureña', StateID: 19 },
                { Municipality: 'Rafael Urdaneta', StateID: 19 },
                { Municipality: 'Samuel Darío Maldonado', StateID: 19 },
                { Municipality: 'San Cristóbal', StateID: 19 },
                { Municipality: 'Seboruco', StateID: 19 },
                { Municipality: 'Simón Rodríguez', StateID: 19 },
                { Municipality: 'Sucre', StateID: 19 },
                { Municipality: 'Torbes', StateID: 19 },
                { Municipality: 'Uribante', StateID: 19 },
                { Municipality: 'San Judas Tadeo', StateID: 19 },
                // Trujillo
                { Municipality: 'Andrés Bello', StateID: 20 },
                { Municipality: 'Boconó', StateID: 20 },
                { Municipality: 'Bolívar', StateID: 20 },
                { Municipality: 'Candelaria', StateID: 20 },
                { Municipality: 'Carache', StateID: 20 },
                { Municipality: 'Escuque', StateID: 20 },
                { Municipality: 'José Felipe Márquez Cañizalez', StateID: 20 },
                { Municipality: 'Juan Vicente Campos Elías', StateID: 20 },
                { Municipality: 'La Ceiba', StateID: 20 },
                { Municipality: 'Miranda', StateID: 20 },
                { Municipality: 'Monte Carmelo', StateID: 20 },
                { Municipality: 'Motatán', StateID: 20 },
                { Municipality: 'Pampán', StateID: 20 },
                { Municipality: 'Pampanito', StateID: 20 },
                { Municipality: 'Rafael Rangel', StateID: 20 },
                { Municipality: 'San Rafael de Carvajal', StateID: 20 },
                { Municipality: 'Sucre', StateID: 20 },
                { Municipality: 'Trujillo', StateID: 20 },
                { Municipality: 'Urdaneta', StateID: 20 },
                { Municipality: 'Valera', StateID: 20 },
                // Vargas
                { Municipality: 'Vargas', StateID: 21 },
                // Yaracuy
                { Municipality: 'Arístides Bastidas', StateID: 22 },
                { Municipality: 'Bolívar', StateID: 22 },
                { Municipality: 'Bruzual', StateID: 22 },
                { Municipality: 'Cocorote', StateID: 22 },
                { Municipality: 'Independencia', StateID: 22 },
                { Municipality: 'José Antonio Páez', StateID: 22 },
                { Municipality: 'La Trinidad', StateID: 22 },
                { Municipality: 'Manuel Monge', StateID: 22 },
                { Municipality: 'Nirgua', StateID: 22 },
                { Municipality: 'Peña', StateID: 22 },
                { Municipality: 'San Felipe', StateID: 22 },
                { Municipality: 'Sucre', StateID: 22 },
                { Municipality: 'Urachiche', StateID: 22 },
                { Municipality: 'Veroes', StateID: 22 },
                // Zulia
                { Municipality: 'Almirante Padilla', StateID: 23 },
                { Municipality: 'Baralt', StateID: 23 },
                { Municipality: 'Cabimas', StateID: 23 },
                { Municipality: 'Catatumbo', StateID: 23 },
                { Municipality: 'Colón', StateID: 23 },
                { Municipality: 'Francisco Javier Pulgar', StateID: 23 },
                { Municipality: 'Jesús Enrique Lossada', StateID: 23 },
                { Municipality: 'Jesús María Semprún', StateID: 23 },
                { Municipality: 'La Cañada de Urdaneta', StateID: 23 },
                { Municipality: 'Lagunillas', StateID: 23 },
                { Municipality: 'Machiques de Perijá', StateID: 23 },
                { Municipality: 'Mara', StateID: 23 },
                { Municipality: 'Maracaibo', StateID: 23 },
                { Municipality: 'Miranda', StateID: 23 },
                { Municipality: 'Páez', StateID: 23 },
                { Municipality: 'Rosario de Perijá', StateID: 23 },
                { Municipality: 'San Francisco', StateID: 23 },
                { Municipality: 'Santa Rita', StateID: 23 },
                { Municipality: 'Simón Bolívar', StateID: 23 },
                { Municipality: 'Sucre', StateID: 23 },
                { Municipality: 'Valmore Rodríguez', StateID: 23 },
                //DISTRITO CAPITAL
                { Municipality: 'Libertador', StateID: 24 },
            ]);
        });
};