exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('parishes').del()
        .then(function () {
            // Inserts seed entries
            return knex('parishes').insert([
                // Amazonas
                { Parish: 'Alto Orinoco', MunicipalityID: 1 },
                { Parish: 'Huachamacare Acanaña', MunicipalityID: 1 },
                { Parish: 'Marawaka Toky Shamanaña', MunicipalityID: 1 },
                { Parish: 'Mavaka Mavaka', MunicipalityID: 1 },
                { Parish: 'Sierra Parima Parimabé', MunicipalityID: 1 },
                { Parish: 'Manapiare', MunicipalityID: 2 },
                { Parish: 'Alto Ventuari', MunicipalityID: 2 },
                { Parish: 'Medio Ventuari', MunicipalityID: 2 },
                { Parish: 'Bajo Ventuari', MunicipalityID: 2 },
                { Parish: 'Atabapo', MunicipalityID: 3 },
                { Parish: 'Ugueto', MunicipalityID: 3 },
                { Parish: 'Yapacana', MunicipalityID: 3 },
                { Parish: 'Caname', MunicipalityID: 3 },
                { Parish: 'Maroa', MunicipalityID: 4 },
                { Parish: 'Victorino', MunicipalityID: 4 },
                { Parish: 'Comunidades', MunicipalityID: 4 },
                { Parish: 'Puerto Ayacucho', MunicipalityID: 5 },
                { Parish: 'Fernando Girón Tovar', MunicipalityID: 5 },
                { Parish: 'Luis Alberto Gómez', MunicipalityID: 5 },
                { Parish: 'Parhueña', MunicipalityID: 5 },
                { Parish: 'Platanillal', MunicipalityID: 5 },
                { Parish: 'Samariapo', MunicipalityID: 6 },
                { Parish: 'Sipapo', MunicipalityID: 6 },
                { Parish: 'Munduapo', MunicipalityID: 6 },
                { Parish: 'Guayapo', MunicipalityID: 6 },
                { Parish: 'San Fernando de Atabapo', MunicipalityID: 7 },
                { Parish: 'Isla Ratón', MunicipalityID: 8 },
                { Parish: 'Guainía', MunicipalityID: 8 },
                { Parish: 'Alto Ventuari', MunicipalityID: 8 },
                // Anzoátegui
                { Parish: 'Anaco', MunicipalityID: 9 },
                { Parish: 'San Joaquín', MunicipalityID: 9 },
                { Parish: 'Cachipo', MunicipalityID: 10 },
                { Parish: 'Aragua de Barcelona', MunicipalityID: 11 },
                { Parish: 'Cachipo', MunicipalityID: 11 },
                { Parish: 'Lechería', MunicipalityID: 12 },
                { Parish: 'El Morro', MunicipalityID: 12 },
                { Parish: 'Puerto Píritu', MunicipalityID: 13 },
                { Parish: 'San Miguel', MunicipalityID: 13 },
                { Parish: 'Sucre', MunicipalityID: 13 },
                { Parish: 'Valle de Guanape', MunicipalityID: 14 },
                { Parish: 'Santa Bárbara', MunicipalityID: 14 },
                { Parish: 'El Chaparro', MunicipalityID: 15 },
                { Parish: 'Tomás Alfaro', MunicipalityID: 15 },
                { Parish: 'Calatrava', MunicipalityID: 15 },
                { Parish: 'Clarines', MunicipalityID: 16 },
                { Parish: 'Guanape', MunicipalityID: 16 },
                { Parish: 'Sabana de Uchire', MunicipalityID: 16 },
                { Parish: 'Onoto', MunicipalityID: 17 },
                { Parish: 'San Pablo', MunicipalityID: 17 },
                { Parish: 'Cantaura', MunicipalityID: 18 },
                { Parish: 'Libertador', MunicipalityID: 18 },
                { Parish: 'Santa Rosa', MunicipalityID: 18 },
                { Parish: 'Urica', MunicipalityID: 18 },
                { Parish: 'Pariaguán', MunicipalityID: 19 },
                { Parish: 'El Pao', MunicipalityID: 20 },
                { Parish: 'Puerto La Cruz', MunicipalityID: 21 },
                { Parish: 'Pozuelos', MunicipalityID: 21 },
                { Parish: 'Píritu', MunicipalityID: 22 },
                { Parish: 'San Francisco', MunicipalityID: 22 },
                { Parish: 'Boca de Uchire', MunicipalityID: 23 },
                { Parish: 'Boca de Chávez', MunicipalityID: 23 },
                { Parish: 'Bergantín', MunicipalityID: 24 },
                { Parish: 'Caigua', MunicipalityID: 24 },
                { Parish: 'El Carmen', MunicipalityID: 24 },
                { Parish: 'El Pilar', MunicipalityID: 24 },
                { Parish: 'Naricual', MunicipalityID: 24 },
                { Parish: 'San Crsitobal', MunicipalityID: 24 },
                { Parish: 'Edmundo Barrios', MunicipalityID: 25 },
                { Parish: 'Miguel Otero Silva', MunicipalityID: 25 },
                // Apure
                { Parish: 'Achaguas', MunicipalityID: 26 },
                { Parish: 'Apurito', MunicipalityID: 26 },
                { Parish: 'El Yagual', MunicipalityID: 26 },
                { Parish: 'Guachara', MunicipalityID: 26 },
                { Parish: 'Mucuritas', MunicipalityID: 26 },
                { Parish: 'Queseras del Medio', MunicipalityID: 26 },
                { Parish: 'Biruaca', MunicipalityID: 27 },
                { Parish: 'Bruzual', MunicipalityID: 28 },
                { Parish: 'Mantecal', MunicipalityID: 28 },
                { Parish: 'Quintero', MunicipalityID: 28 },
                { Parish: 'Rincón Hondo', MunicipalityID: 28 },
                { Parish: 'San Vicente', MunicipalityID: 28 },
                { Parish: 'Guasdualito', MunicipalityID: 29 },
                { Parish: 'Aramendi', MunicipalityID: 29 },
                { Parish: 'El Amparo', MunicipalityID: 29 },
                { Parish: 'San Camilo', MunicipalityID: 29 },
                { Parish: 'Urdaneta', MunicipalityID: 29 },
                { Parish: 'San Juan de Payara', MunicipalityID: 30 },
                { Parish: 'Codazzi', MunicipalityID: 30 },
                { Parish: 'Cunaviche', MunicipalityID: 30 },
                { Parish: 'Elorza', MunicipalityID: 31 },
                { Parish: 'La Trinidad', MunicipalityID: 31 },
                { Parish: 'San Fernando', MunicipalityID: 32 },
                { Parish: 'El Recreo', MunicipalityID: 32 },
                { Parish: 'Peñalver', MunicipalityID: 32 },
                { Parish: 'San Rafael de Atamaica', MunicipalityID: 32 },
                // Aragua
                { Parish: 'Bolívar', MunicipalityID: 33 },
                { Parish: 'Camatagua', MunicipalityID: 34 },
                { Parish: 'Carmen de Cura', MunicipalityID: 34 },
                { Parish: 'Santa Rita', MunicipalityID: 35 },
                { Parish: 'Francisco de Miranda', MunicipalityID: 35 },
                { Parish: 'Monsenor Feliciano Gonzalez', MunicipalityID: 35 },
                { Parish: 'Santa Cruz', MunicipalityID: 36 },
                { Parish: 'Jose Felix Ribas', MunicipalityID: 37 },
                { Parish: 'Castor Nieves Rios', MunicipalityID: 37 },
                { Parish: 'Las Guacamayas', MunicipalityID: 37 },
                { Parish: 'Pao de Zárate', MunicipalityID: 37 },
                { Parish: 'Zuata', MunicipalityID: 37 },
                { Parish: 'José Rafael Revenga', MunicipalityID: 38 },
                { Parish: 'Palo Negro', MunicipalityID: 39 },
                { Parish: 'San Martín de Porres', MunicipalityID: 39 },
                { Parish: 'El Limón', MunicipalityID: 40 },
                { Parish: 'Caña de Azúcar', MunicipalityID: 40 },
                { Parish: 'Ocumare de la Costa', MunicipalityID: 41 },
                { Parish: 'San Casimiro', MunicipalityID: 42 },
                { Parish: 'Güiripa', MunicipalityID: 42 },
                { Parish: 'Ollas de Caramacate', MunicipalityID: 42 },
                { Parish: 'Valle Morin', MunicipalityID: 42 },
                { Parish: 'San Sebastián', MunicipalityID: 43 },
                { Parish: 'Turmero', MunicipalityID: 44 },
                { Parish: 'Arevalo Aponte', MunicipalityID: 44 },
                { Parish: 'Chuao', MunicipalityID: 44 },
                { Parish: 'Samán de Güere', MunicipalityID: 44 },
                { Parish: 'Alfredo Pacheco Miranda', MunicipalityID: 44 },
                { Parish: 'Santos Michelena', MunicipalityID: 45 },
                { Parish: 'Tiara', MunicipalityID: 45 },
                { Parish: 'Cagua', MunicipalityID: 46 },
                { Parish: 'Bella Vista', MunicipalityID: 46 },
                { Parish: 'Tovar', MunicipalityID: 47 },
                { Parish: 'Urdaneta', MunicipalityID: 48 },
                { Parish: 'Las Peñitas', MunicipalityID: 48 },
                { Parish: 'San Francisco de Cara', MunicipalityID: 48 },
                { Parish: 'Taguay', MunicipalityID: 48 },
                { Parish: 'Zuata', MunicipalityID: 49 },
                { Parish: 'La Victoria', MunicipalityID: 50 },
                { Parish: 'El Consejo', MunicipalityID: 50 },
                { Parish: 'Tinaquillo', MunicipalityID: 50 },
                // Barinas
                { Parish: 'Barinas', MunicipalityID: 51 },
                { Parish: 'Alfredo Arvelo Larriva', MunicipalityID: 51 },
                { Parish: 'San Silvestre', MunicipalityID: 51 },
                { Parish: 'Santa Ines', MunicipalityID: 51 },
                { Parish: 'Santa Lucia', MunicipalityID: 51 },
                { Parish: 'Torunos', MunicipalityID: 51 },
                { Parish: 'El Carmen', MunicipalityID: 51 },
                { Parish: 'Rómulo Betancourt', MunicipalityID: 51 },
                { Parish: 'Corazón de Jesús', MunicipalityID: 51 },
                { Parish: 'Ramón Ignacio Méndez', MunicipalityID: 51 },
                { Parish: 'Alto Barinas', MunicipalityID: 51 },
                { Parish: 'Manuel Palacio Fajardo', MunicipalityID: 51 },
                { Parish: 'Juan Antonio Rodríguez Domínguez', MunicipalityID: 51 },
                { Parish: 'Dominga Ortiz de Páez', MunicipalityID: 51 },
                { Parish: 'Barinitas', MunicipalityID: 52 },
                { Parish: 'Altamira de Cáceres', MunicipalityID: 52 },
                { Parish: 'Calderas', MunicipalityID: 52 },
                { Parish: 'Barrancas', MunicipalityID: 53 },
                { Parish: 'El Socorro', MunicipalityID: 53 },
                { Parish: 'Mazparrito', MunicipalityID: 53 },
                { Parish: 'Santa Bárbara', MunicipalityID: 54 },
                { Parish: 'Pedro Briceño Méndez', MunicipalityID: 54 },
                { Parish: 'Ramón Ignacio Méndez', MunicipalityID: 54 },
                { Parish: 'José Ignacio del Pumar', MunicipalityID: 54 },
                { Parish: 'Obispos', MunicipalityID: 55 },
                { Parish: 'Guasimitos', MunicipalityID: 55 },
                { Parish: 'El Real', MunicipalityID: 55 },
                { Parish: 'La Luz', MunicipalityID: 55 },
                { Parish: 'Ciudad Bolivia', MunicipalityID: 56 },
                { Parish: 'Ignacio Briceño', MunicipalityID: 56 },
                { Parish: 'José Félix Ribas', MunicipalityID: 56 },
                { Parish: 'Páez', MunicipalityID: 56 },
                { Parish: 'Libertad', MunicipalityID: 57 },
                { Parish: 'Dolores', MunicipalityID: 57 },
                { Parish: 'Palacio Fajardo', MunicipalityID: 57 },
                { Parish: 'Santa Rosa', MunicipalityID: 57 },
                { Parish: 'Ciudad de Nutrias', MunicipalityID: 58 },
                { Parish: 'El Regalo', MunicipalityID: 58 },
                { Parish: 'Puerto de Nutrias', MunicipalityID: 58 },
                { Parish: 'Santa Catalina', MunicipalityID: 58 },
                { Parish: 'Cachamay', MunicipalityID: 59 },
                { Parish: 'Catedral', MunicipalityID: 59 },
                { Parish: 'Zea', MunicipalityID: 59 },
                { Parish: 'Orinoco', MunicipalityID: 59 },
                { Parish: 'José Antonio Páez', MunicipalityID: 59 },
                { Parish: 'Marhuanta', MunicipalityID: 59 },
                { Parish: 'Agua Salada', MunicipalityID: 59 },
                { Parish: 'Vista Hermosa', MunicipalityID: 59 },
                { Parish: 'La Sabanita', MunicipalityID: 59 },
                { Parish: 'Panapana', MunicipalityID: 59 },
                { Parish: '5 de Julio', MunicipalityID: 60 },
                { Parish: 'Carlos Enrique Álvarez', MunicipalityID: 60 },
                { Parish: 'Los Pijiguaos', MunicipalityID: 60 },
                { Parish: 'Moreno de Mendoza', MunicipalityID: 61 },
                // Bolívar
                { Parish: 'Maripa', MunicipalityID: 62 },
                { Parish: 'Aripao', MunicipalityID: 62 },
                { Parish: 'Guarataro', MunicipalityID: 62 },
                { Parish: 'Las Majadas', MunicipalityID: 62 },
                { Parish: 'Moitaco', MunicipalityID: 62 },
                { Parish: 'Cedeño', MunicipalityID: 63 },
                { Parish: 'Altagracia', MunicipalityID: 63 },
                { Parish: 'Ascención Farreras', MunicipalityID: 63 },
                { Parish: 'Guaniamo', MunicipalityID: 63 },
                { Parish: 'La Urbana', MunicipalityID: 63 },
                { Parish: 'Pijiguaos', MunicipalityID: 63 },
                { Parish: 'El Callao', MunicipalityID: 64 },
                { Parish: 'Gran Sabana', MunicipalityID: 65 },
                { Parish: 'Ikabarú', MunicipalityID: 65 },
                { Parish: '7 de Abril', MunicipalityID: 66 },
                { Parish: 'Santa Bárbara', MunicipalityID: 66 },
                { Parish: 'Pedro Cova', MunicipalityID: 66 },
                { Parish: 'Pedernales', MunicipalityID: 67 },
                { Parish: 'San José', MunicipalityID: 67 },
                { Parish: 'Dalla Costa', MunicipalityID: 68 },
                { Parish: 'Simón Bolívar', MunicipalityID: 68 },
                { Parish: 'Cinco de Julio', MunicipalityID: 68 },
                { Parish: 'José Antonio Páez', MunicipalityID: 68 },
                { Parish: 'Francisco Aniceto Lugo', MunicipalityID: 68 },
                { Parish: 'Andrés Eloy Blanco', MunicipalityID: 68 },
                { Parish: 'Pedro Cova', MunicipalityID: 68 },
                { Parish: 'Raúl Leoni', MunicipalityID: 69 },
                { Parish: 'Barceloneta', MunicipalityID: 69 },
                { Parish: 'Santa Rosalía', MunicipalityID: 69 },
                { Parish: 'Sifontes', MunicipalityID: 70 },
                { Parish: 'Dalla Costa', MunicipalityID: 70 },
                { Parish: 'San Isidro', MunicipalityID: 70 },
                { Parish: 'Ventuari', MunicipalityID: 71 },
                { Parish: 'Manapiare', MunicipalityID: 71 },
                { Parish: 'Casiquiare', MunicipalityID: 71 },
                //Carabobo
                { Parish: 'Bejuma', MunicipalityID: 72 },
                { Parish: 'Canoabo', MunicipalityID: 72 },
                { Parish: 'Simón Bolívar', MunicipalityID: 72 },
                { Parish: 'Güigüe', MunicipalityID: 73 },
                { Parish: 'Carabobo', MunicipalityID: 73 },
                { Parish: 'Tacarigua', MunicipalityID: 73 },
                { Parish: 'Mariara', MunicipalityID: 74 },
                { Parish: 'Aguas Calientes', MunicipalityID: 74 },
                { Parish: 'Ciudad Alianza', MunicipalityID: 75 },
                { Parish: 'Guacara', MunicipalityID: 75 },
                { Parish: 'Yagua', MunicipalityID: 75 },
                { Parish: 'Morón', MunicipalityID: 76 },
                { Parish: 'Urama', MunicipalityID: 76 },
                { Parish: 'Puerto Cabello', MunicipalityID: 77 },
                { Parish: 'Bartolomé Salom', MunicipalityID: 77 },
                { Parish: 'Democracia', MunicipalityID: 77 },
                { Parish: 'Fraternidad', MunicipalityID: 77 },
                { Parish: 'Goaigoaza', MunicipalityID: 77 },
                { Parish: 'Juan José Flores', MunicipalityID: 77 },
                { Parish: 'Unión', MunicipalityID: 77 },
                { Parish: 'Borburata', MunicipalityID: 77 },
                { Parish: 'Patanemo', MunicipalityID: 77 },
                { Parish: 'San Diego', MunicipalityID: 78 },
                { Parish: 'San Joaquín', MunicipalityID: 79 },
                { Parish: 'Mariara', MunicipalityID: 80 },
                { Parish: 'Aguas Calientes', MunicipalityID: 80 },
                { Parish: 'Valencia', MunicipalityID: 81 },
                { Parish: 'Catedral', MunicipalityID: 81 },
                { Parish: 'El Socorro', MunicipalityID: 81 },
                { Parish: 'Miguel Peña', MunicipalityID: 81 },
                { Parish: 'Rafael Urdaneta', MunicipalityID: 81 },
                { Parish: 'San Blas', MunicipalityID: 81 },
                { Parish: 'San José', MunicipalityID: 81 },
                { Parish: 'Santa Rosa', MunicipalityID: 81 },
                { Parish: 'Candelaria', MunicipalityID: 81 },
                { Parish: 'La Pastora', MunicipalityID: 81 },
                { Parish: 'Negro Primero', MunicipalityID: 81 },
                // Cojedes
                { Parish: 'San Carlos de Austria', MunicipalityID: 82 },
                { Parish: 'Juan Angel Bravo', MunicipalityID: 82 },
                { Parish: 'Manuel Manrique', MunicipalityID: 82 },
                { Parish: 'General en Jefe José Laurencio Silva', MunicipalityID: 83 },
                { Parish: 'Macapo', MunicipalityID: 84 },
                { Parish: 'La Aguadita', MunicipalityID: 84 },
                { Parish: 'El Pao', MunicipalityID: 85 },
                { Parish: 'Tinaquillo', MunicipalityID: 86 },
                { Parish: 'El Baúl', MunicipalityID: 87 },
                { Parish: 'Sucre', MunicipalityID: 87 },
                { Parish: 'La Sierra', MunicipalityID: 88 },
                { Parish: 'El Amparo', MunicipalityID: 88 },
                { Parish: 'Libertad de Cojedes', MunicipalityID: 89 },
                { Parish: 'El Baúl', MunicipalityID: 89 },
                { Parish: 'El Pao', MunicipalityID: 90 },
                // Delta Amacuro
                { Parish: 'Curiapo', MunicipalityID: 91 },
                { Parish: 'Almirante Luis Brión', MunicipalityID: 91 },
                { Parish: 'Francisco Aniceto Lugo', MunicipalityID: 91 },
                { Parish: 'Manuel Renaud', MunicipalityID: 91 },
                { Parish: 'Padre Barral', MunicipalityID: 91 },
                { Parish: 'Santos de Abelgas', MunicipalityID: 91 },
                { Parish: 'Imataca', MunicipalityID: 92 },
                { Parish: 'Cinco de Julio', MunicipalityID: 92 },
                { Parish: 'Juan Millán', MunicipalityID: 92 },
                { Parish: 'Leonardo Ruíz Pineda', MunicipalityID: 92 },
                { Parish: 'Mariscal Antonio José de Sucre', MunicipalityID: 92 },
                { Parish: 'Monseñor Argimiro García', MunicipalityID: 92 },
                { Parish: 'San Rafael', MunicipalityID: 92 },
                { Parish: 'Virgen del Valle', MunicipalityID: 92 },
                { Parish: 'Pedernales', MunicipalityID: 93 },
                { Parish: 'Luis Beltrán Prieto Figueroa', MunicipalityID: 93 },
                { Parish: 'Antonio Díaz', MunicipalityID: 94 },
                { Parish: 'Curiapo', MunicipalityID: 94 },
                { Parish: 'Almirante Luis Brión', MunicipalityID: 94 },
                { Parish: 'Francisco Aniceto Lugo', MunicipalityID: 94 },
                { Parish: 'Manuel Renaud', MunicipalityID: 94 },
                { Parish: 'Padre Barral', MunicipalityID: 94 },
                { Parish: 'Santos de Abelgas', MunicipalityID: 94 },
                { Parish: 'Tucupita', MunicipalityID: 95 },
                { Parish: 'San José', MunicipalityID: 95 },
                { Parish: 'Argimiro García', MunicipalityID: 95 },
                { Parish: 'Antonio Díaz', MunicipalityID: 95 },
                { Parish: 'San Rafael', MunicipalityID: 95 },
                { Parish: 'Virgen del Valle', MunicipalityID: 95 },
                // Falcón
                { Parish: 'Cacique Manaure', MunicipalityID: 96 },
                { Parish: 'Norte', MunicipalityID: 97 },
                { Parish: 'Carirubana', MunicipalityID: 97 },
                { Parish: 'Santa Ana', MunicipalityID: 97 },
                { Parish: 'Urbana Punta Cardón', MunicipalityID: 97 },
                { Parish: 'La Vela de Coro', MunicipalityID: 98 },
                { Parish: 'Acurigua', MunicipalityID: 98 },
                { Parish: 'Guaibacoa', MunicipalityID: 98 },
                { Parish: 'Las Calderas', MunicipalityID: 98 },
                { Parish: 'Macoruca', MunicipalityID: 98 },
                { Parish: 'Piedra Grande', MunicipalityID: 99 },
                { Parish: 'Purureche', MunicipalityID: 99 },
                { Parish: 'Pueblo Cumarebo', MunicipalityID: 100 },
                { Parish: 'San Juan de Los Cayos', MunicipalityID: 101 },
                { Parish: 'Capadare', MunicipalityID: 101 },
                { Parish: 'La Pastora', MunicipalityID: 101 },
                { Parish: 'Libertador', MunicipalityID: 101 },
                { Parish: 'San Juan de los Cayos', MunicipalityID: 101 },
                { Parish: 'La Pastora', MunicipalityID: 102 },
                { Parish: 'Aregue', MunicipalityID: 102 },
                { Parish: 'San Agustín', MunicipalityID: 102 },
                { Parish: 'Jacura', MunicipalityID: 103 },
                { Parish: 'Aguada Grande', MunicipalityID: 104 },
                { Parish: 'Churuguara', MunicipalityID: 104 },
                { Parish: 'Píritu', MunicipalityID: 105 },
                { Parish: 'San José de la Costa', MunicipalityID: 105 },
                { Parish: 'Mapararí', MunicipalityID: 106 },
                { Parish: 'Guzmán Guillermo', MunicipalityID: 106 },
                { Parish: 'Mitare', MunicipalityID: 106 },
                { Parish: 'Río Seco', MunicipalityID: 106 },
                { Parish: 'Sabaneta', MunicipalityID: 106 },
                { Parish: 'El Hato', MunicipalityID: 106 },
                { Parish: 'Moruy', MunicipalityID: 106 },
                { Parish: 'Adaure', MunicipalityID: 107 },
                { Parish: 'Adícora', MunicipalityID: 107 },
                { Parish: 'Baraived', MunicipalityID: 107 },
                { Parish: 'Buena Vista', MunicipalityID: 107 },
                { Parish: 'Jadacaquiva', MunicipalityID: 107 },
                { Parish: 'El Vínculo', MunicipalityID: 107 },
                { Parish: 'El Hato', MunicipalityID: 107 },
                { Parish: 'Moruy', MunicipalityID: 107 },
                { Parish: 'Punta Cardón', MunicipalityID: 107 },
                { Parish: 'Mene de Mauroa', MunicipalityID: 108 },
                { Parish: 'San Félix', MunicipalityID: 108 },
                { Parish: 'Casigua', MunicipalityID: 108 },
                { Parish: 'Yaracal', MunicipalityID: 109 },
                { Parish: 'Sabaneta', MunicipalityID: 110 },
                { Parish: 'Mene Mauroa', MunicipalityID: 110 },
                { Parish: 'San Félix', MunicipalityID: 110 },
                { Parish: 'Chichiriviche', MunicipalityID: 111 },
                { Parish: 'Boca de Tocuyo', MunicipalityID: 111 },
                { Parish: 'Bruzual', MunicipalityID: 112 },
                { Parish: 'Uriquina', MunicipalityID: 112 },
                { Parish: 'San Miguel', MunicipalityID: 112 },
                { Parish: 'Moruy', MunicipalityID: 113 },
                { Parish: 'San José de la Costa', MunicipalityID: 113 },
                { Parish: 'Sabana de Mitare', MunicipalityID: 114 },
                { Parish: 'Moruy', MunicipalityID: 114 },
                { Parish: 'Paraguaná', MunicipalityID: 114 },
                { Parish: 'Jacura', MunicipalityID: 115 },
                { Parish: 'Tocuyo de la Costa', MunicipalityID: 115 },
                { Parish: 'Sucre', MunicipalityID: 116 },
                { Parish: 'San Francisco', MunicipalityID: 116 },
                { Parish: 'Pueblo Nuevo', MunicipalityID: 117 },
                { Parish: 'Agua Larga', MunicipalityID: 117 },
                { Parish: 'Santa Cruz de Bucaral', MunicipalityID: 117 },
                { Parish: 'Cabure', MunicipalityID: 118 },
                { Parish: 'Colina', MunicipalityID: 119 },
                { Parish: 'Tocuyo de la Costa', MunicipalityID: 120 },
                { Parish: 'Mizintí', MunicipalityID: 121 },
                { Parish: 'El Vínculo', MunicipalityID: 122 },
                { Parish: 'Purureche', MunicipalityID: 123 },
                { Parish: 'Los Taques', MunicipalityID: 124 },
                { Parish: 'Paraguaná', MunicipalityID: 124 },
                { Parish: 'Mizintí', MunicipalityID: 125 },
                { Parish: 'Mapararí', MunicipalityID: 125 },
                { Parish: 'Tocuyo de la Costa', MunicipalityID: 126 },
                { Parish: 'Mene Mauroa', MunicipalityID: 126 },
                { Parish: 'Capital Carirubana', MunicipalityID: 126 },
                { Parish: 'Santa Ana', MunicipalityID: 126 },
                { Parish: 'Urbana Punta Cardón', MunicipalityID: 126 },
                { Parish: 'Pueblo Nuevo', MunicipalityID: 127 },
                { Parish: 'Agua Larga', MunicipalityID: 127 },
                { Parish: 'Santa Cruz de Bucaral', MunicipalityID: 127 },
                { Parish: 'El Charal', MunicipalityID: 128 },
                { Parish: 'Las Vegas del Tuy', MunicipalityID: 129 },
                { Parish: 'Santa Cruz de Los Taques', MunicipalityID: 130 },
                { Parish: 'San Isidro', MunicipalityID: 130 },
                { Parish: 'Santa Cruz de Los Taques', MunicipalityID: 130 },
                { Parish: 'Venezuela', MunicipalityID: 131 },
                // Guárico
                { Parish: 'Valle de la Pascua', MunicipalityID: 132 },
                { Parish: 'Espino', MunicipalityID: 133 },
                { Parish: 'San José de Unare', MunicipalityID: 133 },
                { Parish: 'San José de Tiznados', MunicipalityID: 134 },
                { Parish: 'San Francisco de Tiznados', MunicipalityID: 134 },
                { Parish: 'San Lorenzo de Tiznados', MunicipalityID: 134 },
                { Parish: 'Ortiz', MunicipalityID: 135 },
                { Parish: 'Guayabal', MunicipalityID: 136 },
                { Parish: 'Cazorla', MunicipalityID: 136 },
                { Parish: 'San José de Guaribe', MunicipalityID: 137 },
                { Parish: 'Uveral', MunicipalityID: 137 },
                { Parish: 'Santa María de Ipire', MunicipalityID: 138 },
                { Parish: 'Altamira', MunicipalityID: 139 },
                { Parish: 'El Yagual', MunicipalityID: 139 },
                { Parish: 'Cantagallo', MunicipalityID: 140 },
                { Parish: 'San Juan de Los Morros', MunicipalityID: 141 },
                { Parish: 'Juan Germán Roscio', MunicipalityID: 142 },
                { Parish: 'Rosario de Paya', MunicipalityID: 142 },
                { Parish: 'Santa Rita de Manapire', MunicipalityID: 142 },
                { Parish: 'San Juan de Los Morros', MunicipalityID: 143 },
                { Parish: 'San José de Guaribe', MunicipalityID: 144 },
                { Parish: 'El Sombrero', MunicipalityID: 145 },
                { Parish: 'Sosa', MunicipalityID: 146 },
                { Parish: 'Libertad de Orituco', MunicipalityID: 147 },
                { Parish: 'San Francisco de Macaira', MunicipalityID: 148 },
                { Parish: 'San Rafael de Orituco', MunicipalityID: 149 },
                { Parish: 'Paso Real de Macaira', MunicipalityID: 149 },
                { Parish: 'Cúa', MunicipalityID: 150 },
                { Parish: 'Nueva Cúa', MunicipalityID: 150 },
                { Parish: 'El Samán', MunicipalityID: 150 },
                { Parish: 'Valles del Tuy', MunicipalityID: 151 },
                { Parish: 'Caucagua', MunicipalityID: 151 },
                { Parish: 'Aragüita', MunicipalityID: 151 },
                { Parish: 'Arévalo González', MunicipalityID: 151 },
                { Parish: 'Capaya', MunicipalityID: 152 },
                { Parish: 'Machurucuto', MunicipalityID: 152 },
                // Lara
                { Parish: 'Siquisique', MunicipalityID: 153 },
                { Parish: 'Moroturo', MunicipalityID: 153 },
                { Parish: 'San Miguel', MunicipalityID: 154 },
                { Parish: 'Carora', MunicipalityID: 154 },
                { Parish: 'Caballete', MunicipalityID: 154 },
                { Parish: 'Antonio Díaz', MunicipalityID: 154 },
                { Parish: 'Agua Viva', MunicipalityID: 155 },
                { Parish: 'Buría', MunicipalityID: 155 },
                { Parish: 'Gustavo Vegas León', MunicipalityID: 155 },
                { Parish: 'Curarigua', MunicipalityID: 156 },
                { Parish: 'La Montañita', MunicipalityID: 156 },
                { Parish: 'Sarare', MunicipalityID: 157 },
                { Parish: 'San José', MunicipalityID: 157 },
                { Parish: 'Sauzal', MunicipalityID: 158 },
                { Parish: 'Tintorero', MunicipalityID: 158 },
                { Parish: 'Yacambú', MunicipalityID: 159 },
                { Parish: 'Concepción', MunicipalityID: 159 },
                { Parish: 'San Rafael', MunicipalityID: 160 },
                { Parish: 'Los Tacarigua', MunicipalityID: 160 },
                { Parish: 'Lara', MunicipalityID:160 },
                { Parish: 'Altagracia', MunicipalityID: 161 },
                { Parish: 'Bolívar', MunicipalityID: 161 },
                { Parish: 'Concepción', MunicipalityID: 161 },
                { Parish: 'Granada', MunicipalityID: 161 },
                { Parish: 'Manuel Morillo', MunicipalityID: 162 },
                { Parish: 'Juan de Villegas', MunicipalityID: 163 },
                { Parish: 'Tocuyito', MunicipalityID: 164 },
                { Parish: 'Independencia', MunicipalityID: 164 },
                { Parish: 'Los Guayos', MunicipalityID: 165 },
                { Parish: 'Miranda', MunicipalityID: 166 },
                { Parish: 'Montalbán', MunicipalityID: 167 },
                { Parish: 'Naguanagua', MunicipalityID: 168 },
                { Parish: 'Bartolomé Salom', MunicipalityID: 169 },
                { Parish: 'Democracia', MunicipalityID: 169 },
                { Parish: 'Fraternidad', MunicipalityID: 169 },
                { Parish: 'Goaigoaza', MunicipalityID: 169 },
                { Parish: 'Juan José Flores', MunicipalityID: 169 },
                { Parish: 'Unión', MunicipalityID: 169 },
                { Parish: 'Borburata', MunicipalityID: 169 },
                { Parish: 'Patanemo', MunicipalityID: 169 },
                { Parish: 'Central Tacarigua', MunicipalityID: 170 },
                { Parish: 'Los Guayos', MunicipalityID: 171 },
                { Parish: 'Mariara', MunicipalityID: 172 },
                { Parish: 'Aguas Calientes', MunicipalityID: 172 },
                { Parish: 'Miguel Peña', MunicipalityID: 173 },
                { Parish: 'Rafael Urdaneta', MunicipalityID: 173 },
                { Parish: 'San Blas', MunicipalityID: 173 },
                { Parish: 'Carabobo', MunicipalityID: 173 },
                { Parish: 'El Socorro', MunicipalityID: 173 },
                { Parish: 'Tocuyito', MunicipalityID: 173 },
                { Parish: 'Independencia', MunicipalityID: 174 },
                { Parish: 'La Democracia', MunicipalityID: 175 },
                { Parish: 'Morón', MunicipalityID: 176 },
                { Parish: 'Yagua', MunicipalityID: 176 },
                { Parish: 'Tacarigua', MunicipalityID: 177 },
                { Parish: 'Mariara', MunicipalityID: 177 },
                { Parish: 'Aguas Calientes', MunicipalityID: 177 },
                { Parish: 'Las Trincheras', MunicipalityID: 178 },
                { Parish: 'Central Tacarigua', MunicipalityID: 179 },
                { Parish: 'Los Guayos', MunicipalityID: 180 },
                { Parish: 'Miranda', MunicipalityID: 181 },
                { Parish: 'Montalbán', MunicipalityID: 182 },
                { Parish: 'Naguanagua', MunicipalityID: 183 },
                { Parish: 'Bartolomé Salom', MunicipalityID: 184 },
                { Parish: 'Democracia', MunicipalityID: 184 },
                { Parish: 'Fraternidad', MunicipalityID: 184 },
                { Parish: 'Goaigoaza', MunicipalityID: 184 },
                { Parish: 'Juan José Flores', MunicipalityID: 184 },
                { Parish: 'Unión', MunicipalityID: 184 },
                { Parish: 'Borburata', MunicipalityID: 184 },
                { Parish: 'Patanemo', MunicipalityID: 184 },
                { Parish: 'San Diego', MunicipalityID: 185 },
                { Parish: 'San Joaquín', MunicipalityID: 186 },
                { Parish: 'Los Guayos', MunicipalityID: 187 },
                { Parish: 'Miranda', MunicipalityID: 188 },
                { Parish: 'Montalbán', MunicipalityID: 189 },
                { Parish: 'Naguanagua', MunicipalityID: 190 },
                { Parish: 'Bartolomé Salom', MunicipalityID: 191 },
                { Parish: 'Democracia', MunicipalityID: 191 },
                { Parish: 'Fraternidad', MunicipalityID: 191 },
                { Parish: 'Goaigoaza', MunicipalityID: 191 },
                { Parish: 'Juan José Flores', MunicipalityID: 191 },
                { Parish: 'Unión', MunicipalityID: 191 },
                { Parish: 'Borburata', MunicipalityID: 191 },
                { Parish: 'Patanemo', MunicipalityID: 191 },
                { Parish: 'San Diego', MunicipalityID: 192 },
                { Parish: 'San Joaquín', MunicipalityID: 193 },
                { Parish: 'Mariara', MunicipalityID: 194 },
                { Parish: 'Aguas Calientes', MunicipalityID: 194 },
                { Parish: 'Valencia', MunicipalityID: 195 },
                { Parish: 'Candelaria', MunicipalityID: 195 },
                { Parish: 'Catedral', MunicipalityID: 195 },
                { Parish: 'El Socorro', MunicipalityID: 195 },
                { Parish: 'Miguel Peña', MunicipalityID: 195 },
                { Parish: 'Rafael Urdaneta', MunicipalityID: 195 },
                { Parish: 'San Blas', MunicipalityID: 195 },
                { Parish: 'San José', MunicipalityID: 195 },
                { Parish: 'Santa Rosa', MunicipalityID: 195 },
                { Parish: 'Negro Primero', MunicipalityID: 195 },
                // Mérida
                { Parish: 'Arapuey', MunicipalityID: 196 },
                { Parish: 'Palmira', MunicipalityID: 197 },
                { Parish: 'San Miguel', MunicipalityID: 198 },
                { Parish: 'Acarigua', MunicipalityID: 199 },
                { Parish: 'Páez', MunicipalityID: 199 },
                { Parish: 'La Trinidad', MunicipalityID: 199 },
                { Parish: 'Mucurubá', MunicipalityID: 200 },
                { Parish: 'Mucuchachí', MunicipalityID: 201 },
                { Parish: 'Fernández Peña', MunicipalityID: 202 },
                { Parish: 'Matriz', MunicipalityID: 202 },
                { Parish: 'Montalbán', MunicipalityID: 202 },
                { Parish: 'Acequias', MunicipalityID: 203 },
                { Parish: 'Jají', MunicipalityID: 203 },
                { Parish: 'La Mesa', MunicipalityID: 203 },
                { Parish: 'San José del Sur', MunicipalityID: 204 },
                { Parish: 'Lagunillas', MunicipalityID: 204 },
                { Parish: 'Agua Viva', MunicipalityID: 205 },
                { Parish: 'Buena Vista', MunicipalityID: 205 },
                { Parish: 'Canela', MunicipalityID: 205 },
                { Parish: 'Chacantá', MunicipalityID: 205 },
                { Parish: 'Estánquez', MunicipalityID: 205 },
                { Parish: 'La Florida', MunicipalityID: 205 },
                { Parish: 'La Mesa', MunicipalityID: 205 },
                { Parish: 'Pueblo Nuevo del Sur', MunicipalityID: 205 },
                { Parish: 'Santa Ana', MunicipalityID: 205 },
                { Parish: 'Zea', MunicipalityID: 205 },
                { Parish: 'Caño El Tigre', MunicipalityID: 206 },
                { Parish: 'Zea', MunicipalityID: 206 },
                { Parish: 'Araguaney', MunicipalityID: 207 },
                { Parish: 'El Jagüito', MunicipalityID: 207 },
                { Parish: 'La Trampa', MunicipalityID: 207 },
                { Parish: 'Pueblo Nuevo', MunicipalityID: 207 },
                { Parish: 'Santa Cruz de Mora', MunicipalityID: 207 },
                { Parish: 'Mesa Bolívar', MunicipalityID: 208 },
                { Parish: 'Mesa de Las Palmas', MunicipalityID: 208 },
                { Parish: 'Aricagua', MunicipalityID: 209 },
                { Parish: 'San Antonio', MunicipalityID: 209 },
                { Parish: 'Canaguá', MunicipalityID: 210 },
                { Parish: 'Capurí', MunicipalityID: 210 },
                { Parish: 'Chacantá', MunicipalityID: 211 },
                { Parish: 'El Molino', MunicipalityID: 211 },
                { Parish: 'Guaimaral', MunicipalityID: 211 },
                { Parish: 'Mucutuy', MunicipalityID: 211 },
                { Parish: 'Mucuchachí', MunicipalityID: 211 },
                { Parish: 'Fernández Peña', MunicipalityID: 212 },
                { Parish: 'Matriz', MunicipalityID: 212 },
                { Parish: 'Montalbán', MunicipalityID: 212 },
                { Parish: 'Acequias', MunicipalityID: 213 },
                { Parish: 'Jají', MunicipalityID: 213 },
                { Parish: 'La Mesa', MunicipalityID: 213 },
                { Parish: 'San José del Sur', MunicipalityID: 214 },
                { Parish: 'Lagunillas', MunicipalityID: 214 },
                { Parish: 'Arapuey', MunicipalityID: 215 },
                { Parish: 'Palmira', MunicipalityID: 216 },
                { Parish: 'San Miguel', MunicipalityID: 217 },
                { Parish: 'Acarigua', MunicipalityID: 218 },
                { Parish: 'Páez', MunicipalityID: 218 },
                { Parish: 'La Trinidad', MunicipalityID: 218 },
                { Parish: 'Mucurubá', MunicipalityID: 219 },
                { Parish: 'Mucuchachí', MunicipalityID: 220 },
                { Parish: 'Fernández Peña', MunicipalityID: 221 },
                { Parish: 'Matriz', MunicipalityID: 221 },
                { Parish: 'Montalbán', MunicipalityID: 221 },
                { Parish: 'Acequias', MunicipalityID: 222 },
                { Parish: 'Jají', MunicipalityID: 222 },
                { Parish: 'La Mesa', MunicipalityID: 222 },
                { Parish: 'San José del Sur', MunicipalityID: 223 },
                { Parish: 'Lagunillas', MunicipalityID: 223 },
                { Parish: 'Arapuey', MunicipalityID: 224 },
                { Parish: 'Palmira', MunicipalityID: 225 },
                { Parish: 'San Miguel', MunicipalityID: 226 },
                { Parish: 'Acarigua', MunicipalityID: 227 },
                { Parish: 'Páez', MunicipalityID: 227 },
                { Parish: 'La Trinidad', MunicipalityID: 227 },
                { Parish: 'Mucurubá', MunicipalityID: 228 },
                { Parish: 'Mucuchachí', MunicipalityID: 229 },
                { Parish: 'Fernández Peña', MunicipalityID: 230 },
                { Parish: 'Matriz', MunicipalityID: 230 },
                { Parish: 'Montalbán', MunicipalityID: 230 },
                { Parish: 'Acequias', MunicipalityID: 231 },
                { Parish: 'Jají', MunicipalityID: 231 },
                { Parish: 'La Mesa', MunicipalityID: 231 },
                { Parish: 'San José del Sur', MunicipalityID: 232 },
                { Parish: 'Lagunillas', MunicipalityID: 232 },
                { Parish: 'Arapuey', MunicipalityID: 233 },
                { Parish: 'Palmira', MunicipalityID: 234 },
                { Parish: 'San Miguel', MunicipalityID: 235 },
                { Parish: 'Acarigua', MunicipalityID: 236 },
                { Parish: 'Páez', MunicipalityID: 236 },
                { Parish: 'La Trinidad', MunicipalityID: 236 },
                { Parish: 'Mucurubá', MunicipalityID: 237 },
                { Parish: 'Mucuchachí', MunicipalityID: 238 },
                { Parish: 'Fernández Peña', MunicipalityID: 239 },
                { Parish: 'Matriz', MunicipalityID: 239 },
                { Parish: 'Montalbán', MunicipalityID: 239 },
                { Parish: 'Acequias', MunicipalityID: 240 },
                { Parish: 'Jají', MunicipalityID: 240 },
                { Parish: 'La Mesa', MunicipalityID: 240 },
                { Parish: 'San José del Sur', MunicipalityID: 241 },
                { Parish: 'Lagunillas', MunicipalityID: 241 },
                { Parish: 'Arapuey', MunicipalityID: 242 },
                { Parish: 'Palmira', MunicipalityID: 243 },
                { Parish: 'San Miguel', MunicipalityID: 244 },
                { Parish: 'Acarigua', MunicipalityID: 245 },
                { Parish: 'Páez', MunicipalityID: 245 },
                { Parish: 'La Trinidad',MunicipalityID: 245 },
                { Parish: 'Mucurubá', MunicipalityID: 246 },
                { Parish: 'Mucuchachí', MunicipalityID: 247 },
                { Parish: 'Fernández Peña', MunicipalityID: 248 },
                { Parish: 'Matriz', MunicipalityID: 248 },
                { Parish: 'Montalbán', MunicipalityID: 248 },
                { Parish: 'Acequias', MunicipalityID: 249 },
                { Parish: 'Jají', MunicipalityID: 249 },
                { Parish: 'La Mesa', MunicipalityID: 249 },
                { Parish: 'San José del Sur', MunicipalityID: 250 },
                { Parish: 'Lagunillas', MunicipalityID: 250 },
                { Parish: 'Arapuey', MunicipalityID: 251 },
                { Parish: 'Palmira', MunicipalityID: 252 },
                { Parish: 'San Miguel', MunicipalityID: 253 },
                { Parish: 'Acarigua', MunicipalityID: 254 },
                { Parish: 'Páez', MunicipalityID: 254 },
                { Parish: 'La Trinidad', MunicipalityID: 254 },
                { Parish: 'Mucurubá', MunicipalityID: 255 },
                { Parish: 'Mucuchachí', MunicipalityID: 256 },
                { Parish: 'Fernández Peña', MunicipalityID: 257 },
                { Parish: 'Matriz', MunicipalityID: 257 },
                { Parish: 'Montalbán', MunicipalityID: 257 },
                { Parish: 'Acequias', MunicipalityID: 258 },
                { Parish: 'Jají', MunicipalityID: 258 },
                { Parish: 'La Mesa', MunicipalityID: 258 },
                { Parish: 'San José del Sur', MunicipalityID: 259 },
                { Parish: 'Lagunillas', MunicipalityID: 259 },
                { Parish: 'Arapuey', MunicipalityID: 260 },
                { Parish: 'Palmira', MunicipalityID: 261 },
                { Parish: 'San Miguel', MunicipalityID: 262 },
                { Parish: 'Acarigua', MunicipalityID: 263 },
                { Parish: 'Páez', MunicipalityID: 263 },
                { Parish: 'La Trinidad', MunicipalityID: 263 },
                { Parish: 'Mucurubá', MunicipalityID: 264 },
                { Parish: 'Mucuchachí', MunicipalityID: 265 },
                { Parish: 'Fernández Peña', MunicipalityID: 266 },
                { Parish: 'Matriz', MunicipalityID: 266 },
                { Parish: 'Montalbán', MunicipalityID: 266 },
                { Parish: 'Acequias', MunicipalityID: 267 },
                { Parish: 'Jají', MunicipalityID: 267 },
                { Parish: 'La Mesa', MunicipalityID: 267 },
                { Parish: 'San José del Sur', MunicipalityID: 268 },
                { Parish: 'Lagunillas', MunicipalityID: 268 },
                { Parish: 'Arapuey', MunicipalityID: 269 },
                { Parish: 'Palmira', MunicipalityID: 270 },
                { Parish: 'San Miguel', MunicipalityID: 271 },
                { Parish: 'Acarigua', MunicipalityID: 272 },
                { Parish: 'Páez', MunicipalityID: 272 },
                { Parish: 'La Trinidad', MunicipalityID: 272 },
                { Parish: 'Mucurubá', MunicipalityID: 273 },
                { Parish: 'Mucuchachí', MunicipalityID: 274 },
                { Parish: 'Fernández Peña', MunicipalityID: 275 },
                { Parish: 'Matriz', MunicipalityID: 275 },
                { Parish: 'Montalbán', MunicipalityID: 275 },
                { Parish: 'Acequias', MunicipalityID: 276 },
                { Parish: 'Jají', MunicipalityID: 276 },
                { Parish: 'La Mesa', MunicipalityID: 276 },
                { Parish: 'San José del Sur', MunicipalityID: 277 },
                { Parish: 'Lagunillas', MunicipalityID: 277 },
                { Parish: 'Arapuey', MunicipalityID: 278 },
                { Parish: 'Palmira', MunicipalityID: 279 },
                { Parish: 'San Miguel', MunicipalityID: 280 },
                { Parish: 'Acarigua', MunicipalityID: 281 },
                { Parish: 'Páez', MunicipalityID: 281 },
                { Parish: 'La Trinidad', MunicipalityID: 281 },
                { Parish: 'Mucurubá', MunicipalityID: 282 },
                { Parish: 'Mucuchachí', MunicipalityID: 283 },
                { Parish: 'Fernández Peña', MunicipalityID: 284 },
                { Parish: 'Matriz', MunicipalityID: 284 },
                { Parish: 'Montalbán', MunicipalityID: 284 },
                { Parish: 'Acequias', MunicipalityID: 285 },
                { Parish: 'Jají', MunicipalityID: 285 },
                { Parish: 'La Mesa', MunicipalityID: 285 },
                { Parish: 'San José del Sur', MunicipalityID: 286 },
                { Parish: 'Lagunillas', MunicipalityID: 286 },
                { Parish: 'Arapuey', MunicipalityID: 287 },
                { Parish: 'Palmira', MunicipalityID: 288 },
                { Parish: 'San Miguel', MunicipalityID: 289 },
                { Parish: 'Acarigua', MunicipalityID: 290 },
                { Parish: 'Páez', MunicipalityID: 290 },
                { Parish: 'La Trinidad', MunicipalityID: 290 },
                { Parish: 'Mucurubá', MunicipalityID: 291 },
                { Parish: 'Mucuchachí', MunicipalityID: 292 },
                { Parish: 'Fernández Peña', MunicipalityID: 293 },
                { Parish: 'Matriz', MunicipalityID: 293 },
                { Parish: 'Montalbán', MunicipalityID: 293 },
                { Parish: 'Acequias', MunicipalityID: 294 },
                { Parish: 'Jají', MunicipalityID: 294 },
                { Parish: 'La Mesa', MunicipalityID: 294 },
                { Parish: 'San José del Sur', MunicipalityID: 295 },
                { Parish: 'Lagunillas', MunicipalityID: 295 },
                { Parish: 'Arapuey', MunicipalityID: 296 },
                { Parish: 'Palmira', MunicipalityID: 297 },
                { Parish: 'San Miguel', MunicipalityID: 298 },
                { Parish: 'Acarigua', MunicipalityID: 299 },
                { Parish: 'Páez', MunicipalityID: 299 },
                { Parish: 'La Trinidad', MunicipalityID: 299 },
                { Parish: 'Mucurubá', MunicipalityID: 300 },
                { Parish: 'Mucuchachí', MunicipalityID: 301 },
                { Parish: 'Fernández Peña', MunicipalityID: 302 },
                { Parish: 'Matriz', MunicipalityID: 302 },
                { Parish: 'Montalbán', MunicipalityID: 302 },
                { Parish: 'Acequias', MunicipalityID: 303 },
                { Parish: 'Jají', MunicipalityID: 303 },
                { Parish: 'La Mesa', MunicipalityID: 303 },
                { Parish: 'San José del Sur', MunicipalityID: 304 },
                { Parish: 'Lagunillas', MunicipalityID: 304 },
                { Parish: 'Arapuey', MunicipalityID: 305 },
                { Parish: 'Palmira', MunicipalityID: 306 },
                { Parish: 'San Miguel', MunicipalityID: 307 },
                { Parish: 'Acarigua', MunicipalityID: 308 },
                { Parish: 'Páez', MunicipalityID: 308 },
                { Parish: 'La Trinidad', MunicipalityID: 308 },
                { Parish: 'Mucurubá', MunicipalityID: 309 },
                { Parish: 'Mucuchachí', MunicipalityID: 310 },
                { Parish: 'Fernández Peña', MunicipalityID: 311 },
                { Parish: 'Matriz', MunicipalityID: 311 },
                { Parish: 'Montalbán', MunicipalityID: 311 },
                { Parish: 'Acequias', MunicipalityID: 312 },
                { Parish: 'Jají', MunicipalityID: 312 },
                { Parish: 'La Mesa', MunicipalityID: 312 },
                { Parish: 'San José del Sur', MunicipalityID: 313 },
                { Parish: 'Lagunillas', MunicipalityID: 313 },
                { Parish: 'Arapuey', MunicipalityID: 314 },
                { Parish: 'Palmira', MunicipalityID: 315 },
                { Parish: 'San Miguel', MunicipalityID: 316 },
                { Parish: 'Acarigua', MunicipalityID: 317 },
                { Parish: 'Páez', MunicipalityID: 317 },
                { Parish: 'La Trinidad', MunicipalityID: 317 },
                { Parish: 'Mucurubá', MunicipalityID: 318 },
                { Parish: 'Mucuchachí', MunicipalityID: 319 },
                { Parish: 'Fernández Peña', MunicipalityID: 320 },
                { Parish: 'Matriz', MunicipalityID: 320 },
                { Parish: 'Montalbán', MunicipalityID: 320 },
                { Parish: 'Acequias', MunicipalityID: 321 },
                { Parish: 'Jají', MunicipalityID: 321 },
                { Parish: 'La Mesa', MunicipalityID: 321 },
                { Parish: 'San José del Sur', MunicipalityID: 322 },
                { Parish: 'Lagunillas', MunicipalityID: 322 },
                { Parish: 'Arapuey', MunicipalityID: 323 },
                { Parish: 'Palmira', MunicipalityID: 324 },
                { Parish: 'San Miguel', MunicipalityID: 325 },
                { Parish: 'Acarigua', MunicipalityID: 326 },
                { Parish: 'Páez', MunicipalityID: 326 },
                { Parish: 'La Trinidad', MunicipalityID: 326 },
                { Parish: 'Mucurubá', MunicipalityID: 327 },
                { Parish: 'Mucuchachí', MunicipalityID: 328 },
                { Parish: 'Fernández Peña', MunicipalityID: 329 },
                { Parish: 'Matriz', MunicipalityID: 329 },
                { Parish: 'Montalbán', MunicipalityID: 329 },
                { Parish: 'Acequias', MunicipalityID: 330 },
                { Parish: 'Jají', MunicipalityID: 330 },
                { Parish: 'La Mesa', MunicipalityID: 330 },
                { Parish: 'San José del Sur', MunicipalityID: 331 },
                { Parish: 'Lagunillas', MunicipalityID: 331 },
                { Parish: 'Arapuey', MunicipalityID: 332 },
                { Parish: 'Palmira', MunicipalityID: 333 },
                { Parish: 'San Miguel', MunicipalityID: 1 },
                { Parish: 'Acarigua', MunicipalityID: 2 },
                { Parish: 'Páez', MunicipalityID: 3 },
                { Parish: 'La Trinidad', MunicipalityID: 4 },
                { Parish: 'Mucurubá', MunicipalityID: 5 },
                { Parish: 'Mucuchachí', MunicipalityID: 6 },
                { Parish: 'Fernández Peña', MunicipalityID: 7 },
                { Parish: 'Matriz', MunicipalityID: 8 },
                { Parish: 'Montalbán', MunicipalityID: 9 },
                { Parish: 'Acequias', MunicipalityID: 10 },
                { Parish: 'Jají', MunicipalityID: 11 },
                { Parish: 'La Mesa', MunicipalityID: 12 },
                { Parish: 'San José del Sur', MunicipalityID: 13 },
                { Parish: 'Lagunillas', MunicipalityID: 14 },
                { Parish: 'Arapuey', MunicipalityID: 15 },
                { Parish: 'Palmira', MunicipalityID: 16 },
                { Parish: 'San Miguel', MunicipalityID: 17 },
                { Parish: 'Acarigua', MunicipalityID: 18 },
                { Parish: 'Páez', MunicipalityID: 19 },
                { Parish: 'La Trinidad', MunicipalityID: 20 },
                { Parish: 'Mucurubá', MunicipalityID: 21 },
                { Parish: 'Mucuchachí', MunicipalityID: 22 },
                { Parish: 'Fernández Peña', MunicipalityID: 23 },
                { Parish: 'Matriz', MunicipalityID: 24 },
                { Parish: 'Montalbán', MunicipalityID: 25 },
                { Parish: 'Acequias', MunicipalityID: 26 },
                { Parish: 'Jají', MunicipalityID: 27 },
                { Parish: 'La Mesa', MunicipalityID: 28 },
                { Parish: 'San José del Sur', MunicipalityID: 29 },
                { Parish: 'Lagunillas', MunicipalityID: 30 },
                { Parish: 'Arapuey', MunicipalityID: 31 },
                { Parish: 'Palmira', MunicipalityID: 32 },
                { Parish: 'San Miguel', MunicipalityID: 33 },
                { Parish: 'Acarigua', MunicipalityID: 34 },
                { Parish: 'Páez', MunicipalityID: 35 },
                { Parish: 'La Trinidad', MunicipalityID: 36 },
                { Parish: 'Mucurubá', MunicipalityID: 37 },
                { Parish: 'Mucuchachí', MunicipalityID: 38 },
                { Parish: 'Fernández Peña', MunicipalityID: 39 },
                { Parish: 'Matriz', MunicipalityID: 40 },
                { Parish: 'Montalbán', MunicipalityID: 41 },
                { Parish: 'Acequias', MunicipalityID: 42 },
                { Parish: 'Jají', MunicipalityID: 43 },
                { Parish: 'La Mesa', MunicipalityID: 44 },
                { Parish: 'San José del Sur', MunicipalityID: 45 },
                { Parish: 'Lagunillas', MunicipalityID: 46 },
                { Parish: 'Arapuey', MunicipalityID: 47 },
                { Parish: 'Palmira', MunicipalityID: 48 },
                { Parish: 'San Miguel', MunicipalityID: 49 },
                { Parish: 'Acarigua', MunicipalityID: 50 },
                { Parish: 'Páez', MunicipalityID: 51 },
                { Parish: 'La Trinidad', MunicipalityID: 52 },
                { Parish: 'Mucurubá', MunicipalityID: 53 },
                { Parish: 'Mucuchachí', MunicipalityID: 54 },
                { Parish: 'Fernández Peña', MunicipalityID: 55 },
                { Parish: 'Matriz', MunicipalityID: 56 },
                { Parish: 'Montalbán', MunicipalityID: 57 },
                { Parish: 'Acequias', MunicipalityID: 58 },
                { Parish: 'Jají', MunicipalityID: 59 },
                { Parish: 'La Mesa', MunicipalityID: 60 },
                { Parish: 'San José del Sur', MunicipalityID: 61 },
                { Parish: 'Lagunillas', MunicipalityID: 62 },
                { Parish: 'Arapuey', MunicipalityID: 63 },
                { Parish: 'Palmira', MunicipalityID: 64 },
                { Parish: 'San Miguel', MunicipalityID: 65 },
                { Parish: 'Acarigua', MunicipalityID: 66 },
                { Parish: 'Páez', MunicipalityID: 67 },
                { Parish: 'La Trinidad', MunicipalityID: 68 },
                { Parish: 'Mucurubá', MunicipalityID: 69 },
                { Parish: 'El Yaco', MunicipalityID: 70 },
                { Parish: 'Abejales', MunicipalityID: 71 },
                { Parish: 'Guanare', MunicipalityID: 72 },
                { Parish: 'Cunaviche', MunicipalityID: 73 },
                { Parish: 'Santa Rosalía', MunicipalityID: 74 },
                { Parish: 'Aparay', MunicipalityID: 75 },
                { Parish: 'Urribarrí', MunicipalityID: 76 },
                { Parish: 'Mesa de Cavacas', MunicipalityID: 77 },
                { Parish: 'Capitanejo', MunicipalityID: 78 },
                { Parish: 'Antolín Tovar', MunicipalityID: 79 },
                { Parish: 'Boconoito', MunicipalityID: 80 },
                { Parish: 'La Estación', MunicipalityID: 81 },
                { Parish: 'Ticoporo', MunicipalityID: 82 },
                { Parish: 'El Amparo', MunicipalityID: 83 },
                { Parish: 'Piedras Negras', MunicipalityID: 84 },
                { Parish: 'La Toscana', MunicipalityID: 85 },
                { Parish: 'Canelones', MunicipalityID: 86 },
                { Parish: 'Uveral', MunicipalityID: 87 },
                { Parish: 'José de la Cruz Vázquez', MunicipalityID: 88 },
                { Parish: 'Villa Rosa', MunicipalityID: 89 },
                { Parish: 'Peña Blanca', MunicipalityID: 90 },
                { Parish: 'Cachamay', MunicipalityID: 91 },
                { Parish: 'Dalla Costa', MunicipalityID: 92 },
                { Parish: 'Simón Bolívar', MunicipalityID: 93 },
                { Parish: 'Puerto Ordaz', MunicipalityID: 94 },
                { Parish: 'San Félix', MunicipalityID: 95 },
                { Parish: 'Pozo Verde', MunicipalityID: 96 },
                { Parish: 'Unare', MunicipalityID: 97 },
                { Parish: 'Zea', MunicipalityID: 98 },
                { Parish: 'Panapana', MunicipalityID: 99 },
                { Parish: 'Andrés Eloy Blanco', MunicipalityID: 100 },
                { Parish: 'Los Barrancos de Fajardo', MunicipalityID: 101 },
                { Parish: 'Cedeño', MunicipalityID: 102 },
                { Parish: 'Guasipati', MunicipalityID: 103 },
                { Parish: 'Salóm', MunicipalityID: 104 },
                { Parish: 'Ikabarú', MunicipalityID: 105 },
                { Parish: 'Cachipo', MunicipalityID: 106 },
                { Parish: 'Tumeremo', MunicipalityID: 107 },
                { Parish: 'El Palmar', MunicipalityID: 108 },
                { Parish: 'El Callao', MunicipalityID: 109 },
                { Parish: 'Gran Sabana', MunicipalityID: 110 },
                { Parish: 'Ikabaru', MunicipalityID: 111 },
                { Parish: 'Dalla Costa', MunicipalityID: 112 },
                { Parish: 'Cachamay', MunicipalityID: 113 },
                { Parish: 'José Antonio Páez', MunicipalityID: 114 },
                { Parish: 'Chirica', MunicipalityID: 115 },
                { Parish: 'Alto Orinoco', MunicipalityID: 116 },
                { Parish: 'Huachamacare Acanaña', MunicipalityID: 117 },
                { Parish: 'Ciudad Guayana', MunicipalityID: 118 },
                { Parish: 'Catedral', MunicipalityID: 119 },
                { Parish: 'Marhuanta', MunicipalityID: 120 },
                { Parish: 'José Gregorio Hernández', MunicipalityID: 121 },
                { Parish: 'Orinoco', MunicipalityID: 122 },
                { Parish: 'José Leonardo Chirinos', MunicipalityID: 123 },
                { Parish: 'Panare', MunicipalityID: 124 },
                { Parish: 'Manoa', MunicipalityID: 125 },
                { Parish: 'Roscio', MunicipalityID: 126 },
                { Parish: 'Sabana de Piedra', MunicipalityID: 127 },
                { Parish: 'San Francisco de Macaira', MunicipalityID: 128 },
                { Parish: 'Vista al Sol', MunicipalityID: 129 },
                { Parish: 'Rivera', MunicipalityID: 130 },
                { Parish: 'Cachamay', MunicipalityID: 131 },
                { Parish: 'Chirica', MunicipalityID: 132 },
                { Parish: 'Dalla Costa', MunicipalityID: 133 },
                { Parish: 'Once de Abril', MunicipalityID: 134 },
                { Parish: 'Simón Bolívar', MunicipalityID: 135 },
                { Parish: 'Unare', MunicipalityID: 136 },
                { Parish: 'Universidad', MunicipalityID: 137 },
                { Parish: 'Vista al Sol', MunicipalityID: 138 },
                { Parish: 'Pozo Verde', MunicipalityID: 139 },
                { Parish: 'Yocoima', MunicipalityID: 140 },
                { Parish: '5 de Julio', MunicipalityID: 141 },
                { Parish: 'Cedeño', MunicipalityID: 142 },
                { Parish: 'Cinco de Julio', MunicipalityID: 143 },
                { Parish: 'Dalla Costa', MunicipalityID: 144 },
                { Parish: 'San Félix', MunicipalityID: 145 },
                { Parish: 'Gran Sabana', MunicipalityID: 146 },
                { Parish: 'Ikabarú', MunicipalityID: 147 },
                { Parish: 'Cachipo', MunicipalityID: 148 },
                { Parish: 'Tumeremo', MunicipalityID: 149 },
                { Parish: 'El Palmar', MunicipalityID: 150 },
                { Parish: '23 de Enero', MunicipalityID: 335 },
                { Parish: 'Altagracia', MunicipalityID: 335 },
                { Parish: 'Antímano', MunicipalityID: 335 },
                { Parish: 'Caricuao', MunicipalityID: 335 },
                { Parish: 'Catedral', MunicipalityID: 335 },
                { Parish: 'Coche', MunicipalityID: 335 },
                { Parish: 'El Junquito', MunicipalityID: 335 },
                { Parish: 'El Paraíso', MunicipalityID: 335 },
            ]);
        });
};