exports.seed = function(knex) {
    // Eliminar todos los registros existentes en la tabla INDUSTRY_TYPE
    return knex('industrytypes').del()
        .then(function() {
            // Insertar los datos en la tabla INDUSTRY_TYPE
            return knex('industrytypes').insert([
                { industrytype: 'Organizaciones sin fines de lucro, beneficencias, MERCAL, PDVAL y similares', sectorid: 1 },
                { industrytype: 'Abastos', sectorid: 2 },
                { industrytype: 'Supermercados', sectorid: 2 },
                { industrytype: 'Hipermercados', sectorid: 2 },
                { industrytype: 'Panaderías, pastelerías y similares', sectorid: 2 },
                { industrytype: 'Automercados', sectorid: 2 },
                { industrytype: 'Charcuterías', sectorid: 2 },
                { industrytype: 'Carnicerías', sectorid: 2 },
                { industrytype: 'Pescaderías', sectorid: 2 },
                { industrytype: 'Fruterías y verdulerías', sectorid: 2 },
                { industrytype: 'Polleras', sectorid: 2 },
                { industrytype: 'Bodegas', sectorid: 2 },
                { industrytype: 'Mercados municipales y ferias de comida', sectorid: 2 },
                { industrytype: 'Otros establecimientos de venta de alimentos', sectorid: 2 },
                { industrytype: 'Aseo urbano', sectorid: 3 },
                { industrytype: 'Suministro de agua', sectorid: 3 },
                { industrytype: 'Suministro de electricidad', sectorid: 3 },
                { industrytype: 'Suministro de gas doméstico', sectorid: 3 },
                { industrytype: 'Servicios de telecomunicaciones', sectorid: 3 },
                { industrytype: 'Servicios de internet', sectorid: 3 },
                { industrytype: 'Servicios de televisión por cable o satelital', sectorid: 3 },
                { industrytype: 'Otros servicios públicos básicos', sectorid: 3 },
                { industrytype: 'Hospitales', sectorid: 4 },
                { industrytype: 'Clínicas', sectorid: 4 },
                { industrytype: 'Laboratorios clínicos', sectorid: 4 },
                { industrytype: 'Farmacias', sectorid: 4 },
                { industrytype: 'Servicios odontológicos', sectorid: 4 },
                { industrytype: 'Servicios de imagenología', sectorid: 4 },
                { industrytype: 'Consultorios médicos', sectorid: 4 },
                { industrytype: 'Ópticas', sectorid: 4 },
                { industrytype: 'Servicios de fisioterapia', sectorid: 4 },
                { industrytype: 'Otros servicios de salud', sectorid: 4 },
                { industrytype: 'Colegios', sectorid: 5 },
                { industrytype: 'Universidades', sectorid: 5 },
                { industrytype: 'Institutos técnicos y tecnológicos', sectorid: 5 },
                { industrytype: 'Guarderías y preescolares', sectorid: 5 },
                { industrytype: 'Academias de idiomas', sectorid: 5 },
                { industrytype: 'Escuelas de arte y música', sectorid: 5 },
                { industrytype: 'Centros de formación profesional', sectorid: 5 },
                { industrytype: 'Centros de educación especial', sectorid: 5 },
                { industrytype: 'Bibliotecas', sectorid: 5 },
                { industrytype: 'Otros servicios educativos', sectorid: 5 },
                { industrytype: 'Tiendas de ropa', sectorid: 6 },
                { industrytype: 'Zapaterías', sectorid: 6 },
                { industrytype: 'Boutiques', sectorid: 6 },
                { industrytype: 'Tiendas de ropa deportiva', sectorid: 6 },
                { industrytype: 'Tiendas de ropa infantil', sectorid: 6 },
                { industrytype: 'Tiendas de ropa y accesorios para el hogar', sectorid: 6 },
                { industrytype: 'Mercados de ropa y calzado', sectorid: 6 },
                { industrytype: 'Tiendas de accesorios y bisutería', sectorid: 6 },
                { industrytype: 'Otros establecimientos de ropa y calzado', sectorid: 6 },
                { industrytype: 'Tiendas de electrodomésticos', sectorid: 7 },
                { industrytype: 'Mueblerías', sectorid: 7 },
                { industrytype: 'Tiendas de artículos para el hogar', sectorid: 7 },
                { industrytype: 'Ferreterías', sectorid: 7 },
                { industrytype: 'Tiendas de decoración', sectorid: 7 },
                { industrytype: 'Tiendas de iluminación', sectorid: 7 },
                { industrytype: 'Tiendas de artículos de cocina', sectorid: 7 },
                { industrytype: 'Tiendas de artículos de limpieza', sectorid: 7 },
                { industrytype: 'Otros establecimientos de equipamiento del hogar', sectorid: 7 },
                { industrytype: 'Cines', sectorid: 8 },
                { industrytype: 'Teatros', sectorid: 8 },
                { industrytype: 'Parques de diversiones', sectorid: 8 },
                { industrytype: 'Centros culturales', sectorid: 8 },
                { industrytype: 'Gimnasios', sectorid: 8 },
                { industrytype: 'Clubes deportivos', sectorid: 8 },
                { industrytype: 'Parques y plazas', sectorid: 8 },
                { industrytype: 'Discotecas y bares', sectorid: 8 },
                { industrytype: 'Restaurantes', sectorid: 8 },
                { industrytype: 'Cafeterías', sectorid: 8 },
                { industrytype: 'Heladerías', sectorid: 8 },
                { industrytype: 'Otros establecimientos de entretenimiento', sectorid: 8 },
                { industrytype: 'Bancos', sectorid: 9 },
                { industrytype: 'Aseguradoras', sectorid: 9 },
                { industrytype: 'Casas de cambio', sectorid: 9 },
                { industrytype: 'Cooperativas de ahorro y crédito', sectorid: 9 },
                { industrytype: 'Instituciones de microfinanzas', sectorid: 9 },
                { industrytype: 'Bolsa de valores', sectorid: 9 },
                { industrytype: 'Fondos de inversión', sectorid: 9 },
                { industrytype: 'Cajas de ahorro', sectorid: 9 },
                { industrytype: 'Otros servicios financieros', sectorid: 9 },
                { industrytype: 'Joyerías', sectorid: 10 },
                { industrytype: 'Tiendas de artículos de lujo', sectorid: 10 },
                { industrytype: 'Tiendas de relojes', sectorid: 10 },
                { industrytype: 'Tiendas de pieles y artículos de cuero', sectorid: 10 },
                { industrytype: 'Tiendas de antigüedades', sectorid: 10 },
                { industrytype: 'Galerías de arte', sectorid: 10 },
                { industrytype: 'Otros bienes suntuarios', sectorid: 10 }
                // Continuar con los registros restantes hasta completar los 129
                // Este bloque es un ejemplo, los valores específicos del SECTOR_ID y otros detalles 
                // de INDUSTRY_TYPE_NAME e INDUSTRY_TYPE_NUMBER deben ser completados según la información completa que tengas.
            ]);
        });
};