exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('point_sale').del()
      .then(function () {
        // Inserts seed entries
        return knex('point_sale').insert([
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174000',
            name: 'Point Sale 1',
            description: 'Description for Point Sale 1',
            pos_details: JSON.stringify({ location: 'Caracas', device: 'POS Terminal' }),
            association_date: '2023-01-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 1,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174001',
            name: 'Point Sale 2',
            description: 'Description for Point Sale 2',
            pos_details: JSON.stringify({ location: 'Valencia', device: 'Mobile POS' }),
            association_date: '2023-02-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 2,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174002',
            name: 'Point Sale 3',
            description: 'Description for Point Sale 3',
            pos_details: JSON.stringify({ location: 'Maracaibo', device: 'Online Payment Gateway' }),
            association_date: '2023-03-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 3,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174003',
            name: 'Point Sale 4',
            description: 'Description for Point Sale 4',
            pos_details: JSON.stringify({ location: 'Barquisimeto', device: 'POS Terminal' }),
            association_date: '2023-04-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 4,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174004',
            name: 'Point Sale 5',
            description: 'Description for Point Sale 5',
            pos_details: JSON.stringify({ location: 'Mérida', device: 'Mobile POS' }),
            association_date: '2023-05-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 5,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174005',
            name: 'Point Sale 6',
            description: 'Description for Point Sale 6',
            pos_details: JSON.stringify({ location: 'Puerto Ordaz', device: 'Online Payment Gateway' }),
            association_date: '2023-06-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 6,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174006',
            name: 'Point Sale 7',
            description: 'Description for Point Sale 7',
            pos_details: JSON.stringify({ location: 'Barcelona', device: 'POS Terminal' }),
            association_date: '2023-07-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 7,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174007',
            name: 'Point Sale 8',
            description: 'Description for Point Sale 8',
            pos_details: JSON.stringify({ location: 'San Cristóbal', device: 'Mobile POS' }),
            association_date: '2023-08-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 8,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174008',
            name: 'Point Sale 9',
            description: 'Description for Point Sale 9',
            pos_details: JSON.stringify({ location: 'Maracay', device: 'Online Payment Gateway' }),
            association_date: '2023-09-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 9,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174009',
            name: 'Point Sale 10',
            description: 'Description for Point Sale 10',
            pos_details: JSON.stringify({ location: 'Cumaná', device: 'POS Terminal' }),
            association_date: '2023-10-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 10,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174010',
            name: 'Point Sale 11',
            description: 'Description for Point Sale 11',
            pos_details: JSON.stringify({ location: 'Ciudad Bolívar', device: 'Mobile POS' }),
            association_date: '2023-11-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 11,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174011',
            name: 'Point Sale 12',
            description: 'Description for Point Sale 12',
            pos_details: JSON.stringify({ location: 'La Guaira', device: 'Online Payment Gateway' }),
            association_date: '2023-12-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 12,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174012',
            name: 'Point Sale 13',
            description: 'Description for Point Sale 13',
            pos_details: JSON.stringify({ location: 'Guarenas', device: 'POS Terminal' }),
            association_date: '2024-01-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 13,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174013',
            name: 'Point Sale 14',
            description: 'Description for Point Sale 14',
            pos_details: JSON.stringify({ location: 'Los Teques', device: 'Mobile POS' }),
            association_date: '2024-02-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 14,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174014',
            name: 'Point Sale 15',
            description: 'Description for Point Sale 15',
            pos_details: JSON.stringify({ location: 'Punto Fijo', device: 'Online Payment Gateway' }),
            association_date: '2024-03-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 15,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174015',
            name: 'Point Sale 16',
            description: 'Description for Point Sale 16',
            pos_details: JSON.stringify({ location: 'Porlamar', device: 'POS Terminal' }),
            association_date: '2024-04-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 16,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174016',
            name: 'Point Sale 17',
            description: 'Description for Point Sale 17',
            pos_details: JSON.stringify({ location: 'Maturín', device: 'Mobile POS' }),
            association_date: '2024-05-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 17,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174017',
            name: 'Point Sale 18',
            description: 'Description for Point Sale 18',
            pos_details: JSON.stringify({ location: 'Cabimas', device: 'Online Payment Gateway' }),
            association_date: '2024-06-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 18,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174018',
            name: 'Point Sale 19',
            description: 'Description for Point Sale 19',
            pos_details: JSON.stringify({ location: 'Acarigua', device: 'POS Terminal' }),
            association_date: '2024-07-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 19,
          },
          {
            pos_GUID:'123e4567-e89b-12d3-a456-426614174019',
            name: 'Point Sale 20',
            description: 'Description for Point Sale 20',
            pos_details: JSON.stringify({ location: 'Santa Teresa del Tuy', device: 'Mobile POS' }),
            association_date: '2024-08-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 20,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174020',
            name: 'Point Sale 21',
            description: 'Description for Point Sale 21',
            pos_details: JSON.stringify({ location: 'Puerto Cabello', device: 'Online Payment Gateway' }),
            association_date: '2024-09-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 21,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174021',
            name: 'Point Sale 22',
            description: 'Description for Point Sale 22',
            pos_details: JSON.stringify({ location: 'Guacara', device: 'POS Terminal' }),
            association_date: '2024-10-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 22,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174022',
            name: 'Point Sale 23',
            description: 'Description for Point Sale 23',
            pos_details: JSON.stringify({ location: 'La Victoria', device: 'Mobile POS' }),
            association_date: '2024-11-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 1,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174023',
            name: 'Point Sale 24',
            description: 'Description for Point Sale 24',
            pos_details: JSON.stringify({ location: 'El Tigre', device: 'Online Payment Gateway' }),
            association_date: '2024-12-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 2,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174024',
            name: 'Point Sale 25',
            description: 'Description for Point Sale 25',
            pos_details: JSON.stringify({ location: 'Guatire', device: 'POS Terminal' }),
            association_date: '2025-01-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 3,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174025',
            name: 'Point Sale 26',
            description: 'Description for Point Sale 26',
            pos_details: JSON.stringify({ location: 'Ocumare del Tuy', device: 'Mobile POS' }),
            association_date: '2025-02-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 4,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174026',
            name: 'Point Sale 27',
            description: 'Description for Point Sale 27',
            pos_details: JSON.stringify({ location: 'El Limón', device: 'Online Payment Gateway' }),
            association_date: '2025-03-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 5,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174027',
            name: 'Point Sale 28',
            description: 'Description for Point Sale 28',
            pos_details: JSON.stringify({ location: 'San Felipe', device: 'POS Terminal' }),
            association_date: '2025-04-15',
            active: true,
            point_sale_category_id: 1,
            business_id: 6,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174028',
            name: 'Point Sale 29',
            description: 'Description for Point Sale 29',
            pos_details: JSON.stringify({ location: 'Araure', device: 'Mobile POS' }),
            association_date: '2025-05-20',
            active: true,
            point_sale_category_id: 1,
            business_id: 7,
          },
          { 
            pos_GUID: '123e4567-e89b-12d3-a456-426614174029',
            name: 'Point Sale 30',
            description: 'Description for Point Sale 30',
            pos_details: JSON.stringify({ location: 'El Vigía', device: 'Online Payment Gateway' }),
            association_date: '2025-06-10',
            active: true,
            point_sale_category_id: 1,
            business_id: 8,
          },
        ]);
      });
  };