exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("orders")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("orders").insert([
        {
          order_number: "ORD001",
          amount: 500.0,
          remaining_balance: 200.0,
          userID: 1,
          saleparameterID: 1,
          businessID: 1,
          created_at: "2024-01-10",
          status: "pendiente",
        },
        {
          order_number: "ORD002",
          amount: 300.5,
          remaining_balance: 0,
          userID: 1,
          saleparameterID: 2,
          businessID: 1,
          created_at: "2024-01-15",
          status: "aprobado",
        },
        {
          order_number: "ORD003",
          amount: 750.75,
          remaining_balance: 500.0,
          userID: 1,
          saleparameterID: 3,
          businessID: 1,
          created_at: "2024-01-20",
          status: "pendiente",
        },
        {
          order_number: "ORD004",
          amount: 1200.0,
          remaining_balance: 1200.0,
          userID: 1,
          saleparameterID: 4,
          businessID: 1,
          created_at: "2024-01-25",
          status: "pendiente",
        },
        {
          order_number: "ORD005",
          amount: 450.0,
          remaining_balance: 0,
          userID: 1,
          saleparameterID: 5,
          businessID: 1,
          created_at: "2024-02-01",
          status: "aprobado",
        },
        {
          order_number: "ORD006",
          amount: 999.99,
          remaining_balance: 99.99,
          userID: 1,
          saleparameterID: 1,
          businessID: 1,
          created_at: "2024-02-10",
          status: "pendiente",
        },
        {
          order_number: "ORD007",
          amount: 650.0,
          remaining_balance: 0,
          userID: 1,
          saleparameterID: 2,
          businessID: 1,
          created_at: "2024-02-12",
          status: "aprobado",
        },
        {
          order_number: "ORD008",
          amount: 900.0,
          remaining_balance: 300.0,
          userID: 1,
          saleparameterID: 3,
          businessID: 1,
          created_at: "2024-02-18",
          status: "pendiente",
        },
        {
          order_number: "ORD009",
          amount: 1100.0,
          remaining_balance: 1100.0,
          userID: 1,
          saleparameterID: 4,
          businessID: 1,
          created_at: "2024-02-20",
          status: "pendiente",
        },
        {
          order_number: "ORD010",
          amount: 275.0,
          remaining_balance: 0,
          userID: 1,
          saleparameterID: 5,
          businessID: 1,
          created_at: "2024-03-01",
          status: "aprobado",
        },
        {
          order_number: "ORD011",
          amount: 600.0,
          remaining_balance: 600.0,
          userID: 1,
          saleparameterID: 1,
          businessID: 1,
          created_at: "2024-03-05",
          status: "pendiente",
        },
        {
          order_number: "ORD012",
          amount: 350.0,
          remaining_balance: 150.0,
          userID: 1,
          saleparameterID: 2,
          businessID: 1,
          created_at: "2024-03-08",
          status: "pendiente",
        },
        {
          order_number: "ORD013",
          amount: 800.0,
          remaining_balance: 0,
          userID: 1,
          saleparameterID: 3,
          businessID: 1,
          created_at: "2024-03-15",
          status: "aprobado",
        },
        {
          order_number: "ORD014",
          amount: 450.0,
          remaining_balance: 450.0,
          userID: 1,
          saleparameterID: 4,
          businessID: 1,
          created_at: "2024-03-18",
          status: "pendiente",
        },
        {
          order_number: "ORD015",
          amount: 999.0,
          remaining_balance: 499.0,
          userID: 1,
          saleparameterID: 5,
          businessID: 1,
          created_at: "2024-03-25",
          status: "pendiente",
        },
        {
          order_number: "ORD016",
          amount: 500.0,
          remaining_balance: 0,
          userID: 1,
          saleparameterID: 1,
          businessID: 1,
          created_at: "2024-04-01",
          status: "aprobado",
        },
        {
          order_number: "ORD017",
          amount: 1050.0,
          remaining_balance: 350.0,
          userID: 1,
          saleparameterID: 2,
          businessID: 1,
          created_at: "2024-04-05",
          status: "pendiente",
        },
        {
          order_number: "ORD018",
          amount: 725.0,
          remaining_balance: 0,
          userID: 1,
          saleparameterID: 3,
          businessID: 1,
          created_at: "2024-04-10",
          status: "aprobado",
        },
        {
          order_number: "ORD019",
          amount: 890.0,
          remaining_balance: 490.0,
          userID: 1,
          saleparameterID: 4,
          businessID: 1,
          created_at: "2024-04-15",
          status: "pendiente",
        },
        {
          order_number: "ORD020",
          amount: 1100.0,
          remaining_balance: 0,
          userID: 1,
          saleparameterID: 5,
          businessID: 1,
          created_at: "2024-04-20",
          status: "aprobado",
        },
      ]);
    });
};
